### PR TITLE
Add an "air hockey" example

### PR DESCRIPTION
**Pull request by vincekurtz**
Adds a simple planar pushing example where one (actuated) puck must push another (unactuated) puck to a desired position and orientation. Builds on #56.

- - -
This change is [Reviewable](https://reviewable.io/reviews/vincekurtz/drake/58)

### CODE REVIEW

**Review by vincekurtz — COMMENTED** [review]
+@amcastro-tri for review please!

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/58#-:-NEaxJdXErvHGW8XBi45:b-6xn0qi)* status: 0 of 19 files reviewed, all discussions resolved (waiting on @amcastro-tri)

**Review by amcastro-tri — CHANGES_REQUESTED** [review]
> Reviewed 6 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/58)* status: 6 of 19 files reviewed, 7 unresolved discussions (waiting on @vincekurtz)

___
*[`traj_opt/solver_parameters.h` line 124 at r1](https://reviewable.io/reviews/vincekurtz/drake/58#-NEgHThzCuOOHJDEY3AP:-NEgHThzCuOOHJDEY3AQ:bl1znjn) ([raw file](https://github.com/vincekurtz/drake/blob/ea4344f10a8393aa64b00c1d7540eea59ce9d3fa/traj_opt/solver_parameters.h#L124)):*
> ```objc
> 
>   bool force_at_a_distance{false};  // whether to allow force at a distance
>   double smoothing_factor{1e2};     // smoothing factor for force at a distance
> ```

btw, I love that now `smoothing_factor = delta`! much simpler and with the right units!
___
*[`traj_opt/trajectory_optimizer.cc` line 347 at r1](https://reviewable.io/reviews/vincekurtz/drake/58#-NEgH-NJ89Ck7gRavkSb:-NEgH-NKESJKrV-aQS_d:b-g5eija) ([raw file](https://github.com/vincekurtz/drake/blob/870907ab123dc0d644b59c4547289ddb951918e7/traj_opt/trajectory_optimizer.cc#L347)):*
> ```cpp
> 
>       // Normal dissipation follows a smoothed Hunt and Crossley model
>       T dissipation_factor = 0.0;
> ```

minor, it might look nicer writing these equations in terms of a dimensionless speed `s = vn / dissipation_velocity`
___
*[`traj_opt/trajectory_optimizer.cc` line 360 at r1](https://reviewable.io/reviews/vincekurtz/drake/58#-NEgGlgq4NF0vGuKty1a:-NEgGlgq4NF0vGuKty1b:bsstkbo) ([raw file](https://github.com/vincekurtz/drake/blob/870907ab123dc0d644b59c4547289ddb951918e7/traj_opt/trajectory_optimizer.cc#L360)):*
> ```cpp
>       // allow for force at a distance.
>       T compliant_fn;
>       if (params_.force_at_a_distance) {
> ```

nit, I'd define `x = -pair.distance/delta` and use it below, since it already appears three times.
___
*[`traj_opt/trajectory_optimizer.cc` line 361 at r1](https://reviewable.io/reviews/vincekurtz/drake/58#-NEgGOiTAOX5CNwRbjDN:-NEgGOiTAOX5CNwRbjDO:b8tdrv1) ([raw file](https://github.com/vincekurtz/drake/blob/870907ab123dc0d644b59c4547289ddb951918e7/traj_opt/trajectory_optimizer.cc#L361)):*
> ```cpp
>       T compliant_fn;
>       if (params_.force_at_a_distance) {
>         if (pair.distance / delta < -100) {
> ```

How do you choose this number 100?

if I do the test `exp(x)+1 == exp(x)` in double floating point precision, those two numbers are equal when x = 37 and different when x= 36.
So it'd seem x=37 is a safer bound to avoid numerical difficulties? WDYT?
___
*[`traj_opt/trajectory_optimizer.cc` line 364 at r1](https://reviewable.io/reviews/vincekurtz/drake/58#-NEkNwvWB6VBEyqjwCj9:-NEkNwvWB6VBEyqjwCjA:b-u7q1k2) ([raw file](https://github.com/vincekurtz/drake/blob/870907ab123dc0d644b59c4547289ddb951918e7/traj_opt/trajectory_optimizer.cc#L364)):*
> ```cpp
>           // If the exponent is going to be very large, replace with the
>           // functional limit as smoothing_factor goes to infinity.
>           compliant_fn = -2 * F / delta * pair.distance;
> ```

Why would we want this factor of 2? wouldn't it be nicer if it wasn't there so that in the limit for large negative distances our normal force goes to `fn = -F*distance/delta`. 
Similarly for large positive delta the limit `f=F*exp(-distance/delta)` reads nice without the factor of 2.
___
*[`traj_opt/examples/airhockey.cc` line 31 at r1](https://reviewable.io/reviews/vincekurtz/drake/58#-NEkONbe-8uBR02Z5eQ3:-NEkONbe-8uBR02Z5eQ4:b-6dh0pm) ([raw file](https://github.com/vincekurtz/drake/blob/870907ab123dc0d644b59c4547289ddb951918e7/traj_opt/examples/airhockey.cc#L31)):*
> ```cpp
> using multibody::UnitInertia;
> 
> class AirHockeyExample : public TrajOptExample {
> ```

btw, nice example!
___
*[`traj_opt/examples/allegro_hand.yaml` line 113 at r1](https://reviewable.io/reviews/vincekurtz/drake/58#-NEkORK15CNOORjAbRV3:-NEkORK15CNOORjAbRV4:b6mdubq) ([raw file](https://github.com/vincekurtz/drake/blob/870907ab123dc0d644b59c4547289ddb951918e7/traj_opt/examples/allegro_hand.yaml#L113)):*
> ```YAML
> # quadratically from 0 Newtons at 0 meters penetration to F Newtons at delta
> # meters of penetration. After this point, force increases linearly at a rate
> # of 2F/delta Newtons / meter. 
> ```

not sure why we want the factor of two in the rate. I think It'd be nice to get rid of it?

**Review by amcastro-tri — COMMENTED** [review]
Actually, I do like the previous version of the force with two parameters, i.e. `fₙ=F/(δσ)⋅ln(1+exp(−σϕ)`.
The reason being that in that original from we have control over the physical model of compliance with stiffness `F/δ` separate from the "action at a distance" controlled by σ.

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/58#-:-NEkURAN56YSglpKjxSK:b-y885i7)* status: 6 of 19 files reviewed, 7 unresolved discussions (waiting on @vincekurtz)

**Review by vincekurtz — COMMENTED** [review]
Makes sense to me. I changed from `fₙ=F⋅ln(1+exp(x)`. to `fₙ=F⋅σ⋅ln(1+exp(x/σ)`, where `x = -ϕ/δ`. Does that make sense in terms of suitably decoupling stiffness and action at a distance?

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/58#-:-NEkzmwp94jnNbfSc9Kd:b-f6ekmi)* status: 3 of 19 files reviewed, 3 unresolved discussions (waiting on @amcastro-tri)

___
*[`traj_opt/trajectory_optimizer.cc` line 361 at r1](https://reviewable.io/reviews/vincekurtz/drake/58#-NEgGOiTAOX5CNwRbjDN:-NEkS_AYETdBnFLaNPAT:b-8om2j5) ([raw file](https://github.com/vincekurtz/drake/blob/870907ab123dc0d644b59c4547289ddb951918e7/traj_opt/trajectory_optimizer.cc#L361)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

How do you choose this number 100?

if I do the test `exp(x)+1 == exp(x)` in double floating point precision, those two numbers are equal when x = 37 and different when x= 36.
So it'd seem x=37 is a safer bound to avoid numerical difficulties? WDYT?
</blockquote></details>

37 sounds good to me: 100 was a pretty arbitrary choice
___
*[`traj_opt/trajectory_optimizer.cc` line 364 at r1](https://reviewable.io/reviews/vincekurtz/drake/58#-NEkNwvWB6VBEyqjwCj9:-NEkT5998TTAg5zGKBQj:buu62xv) ([raw file](https://github.com/vincekurtz/drake/blob/870907ab123dc0d644b59c4547289ddb951918e7/traj_opt/trajectory_optimizer.cc#L364)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Why would we want this factor of 2? wouldn't it be nicer if it wasn't there so that in the limit for large negative distances our normal force goes to `fn = -F*distance/delta`. 
Similarly for large positive delta the limit `f=F*exp(-distance/delta)` reads nice without the factor of 2.
</blockquote></details>

The factor of 2 is to match the slope in the case where there is no force at a distance. In that case (no force at a distance), `fn` increases at a rate of `-2F*distance/delta` when distance is very negative. We can't just use a slope of `-F*distance/delta` in that case, since it would be impossible to connect the points `(0,0)` and `(-delta, F)` with a smooth quadratic. Let me know if that doesn't make sense: I can try to draw a picture which might be more helpful
___
*[`traj_opt/examples/allegro_hand.yaml` line 113 at r1](https://reviewable.io/reviews/vincekurtz/drake/58#-NEkORK15CNOORjAbRV3:-NEkUF3J4KFcw04Rm6Uj:b-3a472v) ([raw file](https://github.com/vincekurtz/drake/blob/870907ab123dc0d644b59c4547289ddb951918e7/traj_opt/examples/allegro_hand.yaml#L113)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

not sure why we want the factor of two in the rate. I think It'd be nice to get rid of it?
</blockquote></details>

See comment above: I don't think it's possible to both smoothly switch over at the point `(-delta,F)` and have the slope be `F/delta`. We could have a slope of `F/delta` if we switched from quadratic to linear at `(-2delta, F)`. I don't have a strong opinion on which placement of the factor of 2 is better - but it needs to be in there somewhere.

**Pull request merged**
