### PR TITLE
Optimization Through Contact Without Friction

### PR DESCRIPTION
**Pull request by vincekurtz**
Add the ability to do very basic optimization through contact. 

This is a rather large PR, with several main components:
- Add (normal component of) contact forces into inverse dynamics computations
- Add an example of pushing a spinner
- Reorganize examples to minimize repeated code
- Implement trust-region (dogleg) solver

- - -
This change is [Reviewable](https://reviewable.io/reviews/vincekurtz/drake/27)

### CODE REVIEW

**Review by vincekurtz — COMMENTED** [review]
+@amcastro-tri for feature review please

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/27#-:-N9lOlpl8tzGRZeDZoUU:brbsdox)* status: 0 of 31 files reviewed, all discussions resolved (waiting on @amcastro-tri)

**Review by amcastro-tri — CHANGES_REQUESTED** [review]
working....

> Reviewed 2 of 18 files at r3, 1 of 5 files at r4, 7 of 28 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/27#-:-NA9sw8GEopA6prs5tna:b-hkkp2s)* status: 10 of 31 files reviewed, 5 unresolved discussions (waiting on @amcastro-tri and @vincekurtz)

___
*[`traj_opt/penta_diagonal_matrix.h` line 96 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NA9oiyhEnK2EolOdbYR:-NA9oiyi5fVXF6O9j4-g:b-6a9u2f) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/penta_diagonal_matrix.h#L96)):*
> ```objc
> 
>   // Multiply this matrix by a vector of the correct size
>   VectorX<T> MultiplyBy(const VectorX<T>& v) const;
> ```

this will heap allocate a new vector everytime you call it.
Usually better if you let the caller allocate. Like in `MultiplyBy(const VectorX<T>& v, VectorX<T>* y) const;`
___
*[`traj_opt/penta_diagonal_matrix.cc` line 183 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NA9oxvuCuuUsqM7YRbP:-NA9oxvuCuuUsqM7YRbQ:b-kw5wvm) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/penta_diagonal_matrix.cc#L183)):*
> ```cpp
> VectorX<T> PentaDiagonalMatrix<T>::MultiplyBy(const VectorX<T>& v) const {
>   DRAKE_DEMAND(v.size() == rows());
>   const int bs = block_size();
> ```

haha, you gotta love the name of this variable.
___
*[`traj_opt/solver_parameters.h` line 41 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NA9pRCsAuwxx8B8gq9_:-NA9pRCsAuwxx8B8gq9a:b7z9dt6) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/solver_parameters.h#L41)):*
> ```objc
> 
>   // Flag for whether to record linesearch data to a file at each iteration (for
>   // later plotting)
> ```

minor, add a line saying "where" it gets recorded and where to go look for that recorded data.
___
*[`traj_opt/trajectory_optimizer_state.h` line 99 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NA9pujmBHL9OwFPFRlW:-NA9pujmBHL9OwFPFRlX:b-r8k0mu) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/trajectory_optimizer_state.h#L99)):*
> ```objc
>   // H_diag = [diag(C0), diag(C1), diag(C2), ...]
>   //
>   std::vector<VectorX<T>> H_diag;
> ```

I haven't seen how it gets used yet, but wouldn't it be easier to store it as a contiguous `VectorX` for usage later? ditto for `q_last`.
ignore if not.
___
*[`traj_opt/trajectory_optimizer_state.h` line 204 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NA9qMcO9OYa5vXJncvI:-NA9qMcO9OYa5vXJncvJ:b3ux76b) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/trajectory_optimizer_state.h#L204)):*
> ```objc
>   void set_proximal_operator_data(const std::vector<VectorX<T>>& q,
>                                   const PentaDiagonalMatrix<T>& H) {
>     // Set previous decision variables
> ```

shouldn't we invalidate the cache here? cost L, gradient g, and Hessian H will be invalidated?
___
*[`traj_opt/test/penta_diagonal_solver_test.cc` line 17 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NA9rQZCDjvJKoPiPFRr:-NA9rQZCDjvJKoPiPFRs:b-1b3uo0) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/test/penta_diagonal_solver_test.cc#L17)):*
> ```cpp
> namespace internal {
> 
> GTEST_TEST(PentaDiagonalMatrixTest, MultiplyBy) {
> ```

btw, nice test!
___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 226 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NA9s_poA4uhKDLoUQN6:-NA9s_poA4uhKDLoUQN7:bbb3j1r) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/test/trajectory_optimizer_test.cc#L226)):*
> ```cpp
>   VectorXd dq = -g;
>   PentaDiagonalFactorization Hchol(H);
>   Hchol.SolveInPlace(&dq);
> ```

This is a nice test!

Actually, here dq can be chosen arbitrarily. In particular, you could choose an arbitrary direction (normalized), and then evaluate the trust ratio for different norms of dq to see how/if round-off errors affect the result.

**Review by amcastro-tri — CHANGES_REQUESTED** [review]
This is awesome. Only minor comments.
:lgtm_strong: 

> Reviewed 21 of 28 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/27#-:-NAA7IP50W0WujI32_IZ:b-yajhtr)* status: all files reviewed (commit messages unreviewed), 12 unresolved discussions (waiting on @vincekurtz)

___
*[`traj_opt/trajectory_optimizer.cc` line 71 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NA9zmY31bzqgjm3y2Y2:-NA9zmY43K7bDz-oX6oo:bm6q4b8) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/trajectory_optimizer.cc#L71)):*
> ```cpp
>     for (int t = 0; t <= num_steps(); ++t) {
>       cost += T(0.5 * params_.rho_proximal * (q[t] - q_last[t]).transpose() *
>                 H_diag[t].asDiagonal() * (q[t] - q_last[t]));
> ```

nit, if you save H_diag and q_last as `VectorX<T>`, the for loop would go away and this would reduce to ta one liner.
___
*[`traj_opt/trajectory_optimizer.cc` line 526 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NAA-XPW50NJqFmN4f-h:-NAA-XPW50NJqFmN4f-i:b-6rt6cp) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/trajectory_optimizer.cc#L526)):*
> ```cpp
>     for (int t = 0; t <= num_steps(); ++t) {
>       g->segment(t * nq, nq) +=
>           params_.rho_proximal * H_diag[t].asDiagonal() * (q[t] - q_last[t]);
> ```

ditto, this could be a one linear if H_diag and q_last are saved as VectorX.
___
*[`traj_opt/trajectory_optimizer.cc` line 613 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NAA-lbG-i7HgEtSihfI:-NAA-lbG-i7HgEtSihfJ:b-ieg0b2) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/trajectory_optimizer.cc#L613)):*
> ```cpp
>     for (int t = 0; t <= num_steps(); ++t) {
>       C[t] += params_.rho_proximal *
>               state.proximal_operator_data().H_diag[t].asDiagonal();
> ```

if stored as VectorX, you'd do `C[t] += rho * H_diag.segment(t*nq, nq).asDiagonal();
___
*[`traj_opt/trajectory_optimizer.cc` line 911 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NAA1SJ08cmloD8s9dF_:-NAA1SJ08cmloD8s9dFa:b-h6b1wi) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/trajectory_optimizer.cc#L911)):*
> ```cpp
>     // large enough that we accept dq, but not so large that we increase the
>     // trust region.
>     return 0.4;
> ```

is this criteria what you've been using lately? 
Just wondering if this needs an update.
___
*[`traj_opt/trajectory_optimizer.cc` line 965 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NAA2AF_0Nt-J5_fDKaT:-NAA2AF_0Nt-J5_fDKaU:b32488c) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/trajectory_optimizer.cc#L965)):*
> ```cpp
>   const PentaDiagonalMatrix<double>& H = EvalHessian(state);
>   const double gHg = g.transpose() * H.MultiplyBy(g);
> ```

minor, please add a note possibly here at the top, that you are normalizing all these vectors with `Delta` to minimize round-off errors.
___
*[`traj_opt/trajectory_optimizer.cc` line 995 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NAA2JJ52wbO5aQQGL-3:-NAA2JJ52wbO5aQQGL-4:b-hdv174) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/trajectory_optimizer.cc#L995)):*
> ```cpp
>   // trust region. We'll do this by solving the (scalar) quadratic
>   //
>   //    ‖ pU + s( pH − pU ) ‖² = Δ²
> ```

nit, please mention how you normalized this equation to minimize round-off errors.
___
*[`traj_opt/trajectory_optimizer.cc` line 1245 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NAA31mp5ldPKM7rjWim:-NAA31mp5ldPKM7rjWin:b-hdn55d) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/trajectory_optimizer.cc#L1245)):*
> ```cpp
> 
>   // Trust region parameters
>   const double Delta_max = 1000;  // Maximum trust region size
> ```

this seems to arbitrary? say for 1 m displacement or 1 radian, then the maximum norm of dq would be sqrt(dq.size())?

**Review by vincekurtz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/27)* status: all files reviewed (commit messages unreviewed), 9 unresolved discussions (waiting on @amcastro-tri and @vincekurtz)

___
*[`traj_opt/penta_diagonal_matrix.h` line 96 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NA9oiyhEnK2EolOdbYR:-NABxLp4EBpqmk-G8HnH:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/penta_diagonal_matrix.h#L96)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

this will heap allocate a new vector everytime you call it.
Usually better if you let the caller allocate. Like in `MultiplyBy(const VectorX<T>& v, VectorX<T>* y) const;`
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.cc` line 71 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NA9zmY31bzqgjm3y2Y2:-NABp2Qh7G2vNV2XF3YM:b-6h62cj) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/trajectory_optimizer.cc#L71)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nit, if you save H_diag and q_last as `VectorX<T>`, the for loop would go away and this would reduce to ta one liner.
</blockquote></details>

You'd still have to put q[t] into a `VectorX<T>` somehow, so I'm not convinced this would really save that much. I'll hold off on this change for now, with the knowledge that this could be implemented later if we really want it. 
___
*[`traj_opt/trajectory_optimizer.cc` line 911 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NAA1SJ08cmloD8s9dF_:-NABojyy4UoaKSmK4Xih:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/trajectory_optimizer.cc#L911)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

is this criteria what you've been using lately? 
Just wondering if this needs an update.
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.cc` line 1245 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NAA31mp5ldPKM7rjWim:-NABnCrf5eESyhe_D5aM:bidcljk) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/trajectory_optimizer.cc#L1245)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

this seems to arbitrary? say for 1 m displacement or 1 radian, then the maximum norm of dq would be sqrt(dq.size())?
</blockquote></details>

Fair enough, set to 1 (meter or radian) for this reason. 
___
*[`traj_opt/trajectory_optimizer_state.h` line 204 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NA9qMcO9OYa5vXJncvI:-NABmrEr5hbvfTJqs0ix:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/trajectory_optimizer_state.h#L204)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

shouldn't we invalidate the cache here? cost L, gradient g, and Hessian H will be invalidated?
</blockquote></details>

Done.
___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 226 at r5](https://reviewable.io/reviews/vincekurtz/drake/27#-NA9s_poA4uhKDLoUQN6:-NABlrLQ0N43Hhqz2fZn:bz7bgvf) ([raw file](https://github.com/vincekurtz/drake/blob/cf2faf4621acb123306af0dcc986dad15f47a736/traj_opt/test/trajectory_optimizer_test.cc#L226)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

This is a nice test!

Actually, here dq can be chosen arbitrarily. In particular, you could choose an arbitrary direction (normalized), and then evaluate the trust ratio for different norms of dq to see how/if round-off errors affect the result.
</blockquote></details>

From today's plots, the trust ratio only makes sense over those dq where the quadratic model predicts a reduction in the cost. Otherwise the denominator goes to zero and we have a strange indeterminate flipping behavior.

**Pull request merged**
