### PR TITLE
Implements computation of v as a function of q

### PR DESCRIPTION
**Pull request by vincekurtz**
Adds a simple helper function to compute generalized velocities (v) as a function of generalized positions (q), where 
```
v_t = (q_t - q_{t-1}) / dt
```

Adds a simple unit test for this as well, based on simulating a simple pendulum.

---
This change is [Reviewable](https://reviewable.io/reviews/vincekurtz/drake/14)

### CODE REVIEW

**Review by vincekurtz — COMMENTED** [review]
+@amcastro-tri for feature review please

(I will rebase once #12 has landed, which should make this much easier to review)

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/14#-:-N7gEvch6PysScLy6KOz:b-kyjokv)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @amcastro-tri)

___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 81 at r1](https://reviewable.io/reviews/vincekurtz/drake/14#-N7gFRI-1soaCbgIObBa:-N7gFRI-1soaCbgIObBb:b-i69tpo) ([raw file](https://github.com/vincekurtz/drake/blob/582d2d83e2cd9a2d3bbfde9e57ca680e70f6dbe4/traj_opt/test/trajectory_optimizer_test.cc#L81)):*
> ```cpp
>   }
> 
>   const double kTolerance = std::numeric_limits<double>::epsilon() * 100;
> ```

How does one properly compute this tolerance?

**Review by amcastro-tri — CHANGES_REQUESTED** [review]
per f2f. We'll grab snippets of #12 as we need on new PRs.

> Reviewed 1 of 11 files at r1, 6 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/14#-:-N7q_yN77MEFvNpAE_2h:badrw)* status: 7 of 11 files reviewed, 8 unresolved discussions (waiting on @amcastro-tri and @vincekurtz)

___
*[`traj_opt/problem_definition.h` line 24 at r2](https://reviewable.io/reviews/vincekurtz/drake/14#-N7qcllh6q472fTXsEqv:-N7qcllh6q472fTXsEqw:bko6tn3) ([raw file](https://github.com/vincekurtz/drake/blob/efecb55d11f612e2bcd977b142dd77ee9857f1d8/traj_opt/problem_definition.h#L24)):*
> ```objc
> struct ProblemDefinition {
>   // Time horizon (number of steps) for the optimization problem
>   int T;
> ```

ah... I see now. In your ` TrajectoryOptimizer` this becomes a `double`. If the number of steps, then maybe call it `num_steps()` or `num_nodes()`?
___
*[`traj_opt/problem_definition.h` line 27 at r2](https://reviewable.io/reviews/vincekurtz/drake/14#-N7qd-Y-9m0QYnlivDeu:-N7qd-Y-9m0QYnlivDev:b2apld8) ([raw file](https://github.com/vincekurtz/drake/blob/efecb55d11f612e2bcd977b142dd77ee9857f1d8/traj_opt/problem_definition.h#L27)):*
> ```objc
> 
>   // Running cost coefficients for generalized positions
>   MatrixXd Qq;
> ```

I'd say that whatev you do not need in this PR do not include it.

For instance, It'd seem that all of these should probably be `std::vector<MatrixXd>` instead. However right now we cannot tell simply because we do not have code that uses it. 
___
*[`traj_opt/trajectory_optimizer.h` line 26 at r2](https://reviewable.io/reviews/vincekurtz/drake/14#-N7qcPQB3JQKYexDkAlr:-N7qcPQB3JQKYexDkAls:b-titr0l) ([raw file](https://github.com/vincekurtz/drake/blob/efecb55d11f612e2bcd977b142dd77ee9857f1d8/traj_opt/trajectory_optimizer.h#L26)):*
> ```objc
>    *             etc.
>    */
>   TrajectoryOptimizer(std::unique_ptr<const MultibodyPlant<double>> plant,
> ```

nit, do we wanna transfer ownership here? that'd mean that the application code that calls this needs to give up the plant and cannot use it later on (consider for instance I wanna solve my traj opt and the visualize something with the same plant)
I'd recommend here you take a `const MultibodyPlant<double>* plant` instead.
___
*[`traj_opt/trajectory_optimizer.h` line 39 at r2](https://reviewable.io/reviews/vincekurtz/drake/14#-N7qazvh41AMRc8aJGGY:-N7qazvh41AMRc8aJGGZ:b-n7o7h1) ([raw file](https://github.com/vincekurtz/drake/blob/efecb55d11f612e2bcd977b142dd77ee9857f1d8/traj_opt/trajectory_optimizer.h#L39)):*
> ```objc
>    * Convienience function to get the time horizon of this optimization problem.
>    *
>    * @return double T, the number of time steps in the optimal trajectory.
> ```

the number of time steps? a `double`? either the docs or the return type are wrong?
Also, we use `T` all over the place in Drake to indicate the scalar type. So even if we work with `double` everywhere, do not use such a shorthand notation. 
Typically in Drake we lean on the side of verbosity when possible, [we even have a section on this on our style guide, fyi](https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules).

In this case I'd say you name to `time_horizon` or `number_of_nodes()` or whatev depending on the actual return
___
*[`traj_opt/trajectory_optimizer.h` line 49 at r2](https://reviewable.io/reviews/vincekurtz/drake/14#-N7qbuJD793SaL9AeXrU:-N7qbuJD793SaL9AeXrV:b-ohdg3) ([raw file](https://github.com/vincekurtz/drake/blob/efecb55d11f612e2bcd977b142dd77ee9857f1d8/traj_opt/trajectory_optimizer.h#L49)):*
> ```objc
>    *     v_t = (q_t - q_{t-1})/dt
>    *
>    * and v_0 is defined by the initial state of the optimization problem.
> ```

This one is interesting to document for our convenions.
So if I understand correctly, the expression above is only valid of t=1:num_nodes()? I'd recommend to document that so that we start getting used to sizes and indexes.

Also, what is the size of `q` and `v`? are they the same size? are they of size num_nodes() or num_nodes()+1?
___
*[`traj_opt/trajectory_optimizer.cc` line 16 at r2](https://reviewable.io/reviews/vincekurtz/drake/14#-N7qdbOf1eTqIGR9OAB8:-N7qdbOf1eTqIGR9OAB9:b-j4hj7g) ([raw file](https://github.com/vincekurtz/drake/blob/efecb55d11f612e2bcd977b142dd77ee9857f1d8/traj_opt/trajectory_optimizer.cc#L16)):*
> ```cpp
>     : prob_(prob) {
>   plant_ = std::move(plant);
>   context_ = plant_->CreateDefaultContext();
> ```

fyi, here you might want a reference to the containing Diagram as well. 
The reason being that you'll need a `context` for the entire model, including geometry.
We can fix that as we add contact, but I figure you'd want to know.
I think the easy fix is to change the signature to `TrajectoryOptimzer(const System<double>& container_diagram, MultibodyPlant<double>* plant, ProblemDefinition prob)`
___
*[`traj_opt/trajectory_optimizer.cc` line 25 at r2](https://reviewable.io/reviews/vincekurtz/drake/14#-N7qkZ3d-jd26tcke6Ci:-N7qkZ3d-jd26tcke6Cj:buspc0s) ([raw file](https://github.com/vincekurtz/drake/blob/efecb55d11f612e2bcd977b142dd77ee9857f1d8/traj_opt/trajectory_optimizer.cc#L25)):*
> ```cpp
>   DRAKE_DEMAND(static_cast<int>(v->size()) == T() + 1);
> 
>   v->at(0) = prob_.v_init;
> ```

do we need `v_init`? does it enter into the formulation at all?
___
*[`traj_opt/examples/pendulum.urdf` line 2 at r2](https://reviewable.io/reviews/vincekurtz/drake/14#-N7qkKsQA7F_EYui-Y9x:-N7qkKsQA7F_EYui-Y9y:b-b7k819) ([raw file](https://github.com/vincekurtz/drake/blob/efecb55d11f612e2bcd977b142dd77ee9857f1d8/traj_opt/examples/pendulum.urdf#L2)):*
> ```XML
> <?xml version="1.0"?>
> <robot name="Pendulum">
> ```

try to reuse this file if an exact copy of the one in Drake master.
A global search of `pendulum.urdf` reveals it gets used in about 30 places. So there is a way to use it?

**Review by amcastro-tri — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/14)* status: 9 of 11 files reviewed, 9 unresolved discussions (waiting on @amcastro-tri and @vincekurtz)

___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 33 at r2](https://reviewable.io/reviews/vincekurtz/drake/14#-N7qnksP6wt0SwaQRUij:-N7qnksP6wt0SwaQRUik:b58y870) ([raw file](https://github.com/vincekurtz/drake/blob/efecb55d11f612e2bcd977b142dd77ee9857f1d8/traj_opt/test/trajectory_optimizer_test.cc#L33)):*
> ```cpp
>   auto plant = std::make_unique<MultibodyPlant<double>>(1e-2);
>   const std::string urdf_file =
>       FindResourceOrThrow("drake/traj_opt/examples/pendulum.urdf");
> ```

This is a very complex way to test `CalcV()`.
Here is a simpler case: consider a constant velocity. Since you are using backward differencing, which is first order, you should at least check that if you provide a linear function `q(t)` you get a constant `v(t)` everywhere.

**Review by vincekurtz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/14)* status: 4 of 11 files reviewed, 7 unresolved discussions (waiting on @amcastro-tri)

___
*[`traj_opt/problem_definition.h` line 24 at r2](https://reviewable.io/reviews/vincekurtz/drake/14#-N7qcllh6q472fTXsEqv:-N7qxJsEADISz6ZjyC0V:bkadc9g) ([raw file](https://github.com/vincekurtz/drake/blob/efecb55d11f612e2bcd977b142dd77ee9857f1d8/traj_opt/problem_definition.h#L24)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

ah... I see now. In your ` TrajectoryOptimizer` this becomes a `double`. If the number of steps, then maybe call it `num_steps()` or `num_nodes()`?
</blockquote></details>

Done. My bad on the idiotic double conversion.
___
*[`traj_opt/problem_definition.h` line 27 at r2](https://reviewable.io/reviews/vincekurtz/drake/14#-N7qd-Y-9m0QYnlivDeu:-N7r7aj69tBkBcNfiGKc:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/efecb55d11f612e2bcd977b142dd77ee9857f1d8/traj_opt/problem_definition.h#L27)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I'd say that whatev you do not need in this PR do not include it.

For instance, It'd seem that all of these should probably be `std::vector<MatrixXd>` instead. However right now we cannot tell simply because we do not have code that uses it. 
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.h` line 39 at r2](https://reviewable.io/reviews/vincekurtz/drake/14#-N7qazvh41AMRc8aJGGY:-N7r8qnwB_cY579xDXqt:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/efecb55d11f612e2bcd977b142dd77ee9857f1d8/traj_opt/trajectory_optimizer.h#L39)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

the number of time steps? a `double`? either the docs or the return type are wrong?
Also, we use `T` all over the place in Drake to indicate the scalar type. So even if we work with `double` everywhere, do not use such a shorthand notation. 
Typically in Drake we lean on the side of verbosity when possible, [we even have a section on this on our style guide, fyi](https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules).

In this case I'd say you name to `time_horizon` or `number_of_nodes()` or whatev depending on the actual return
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.h` line 49 at r2](https://reviewable.io/reviews/vincekurtz/drake/14#-N7qbuJD793SaL9AeXrU:-N7r9nSj42FOLPhWC_R1:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/efecb55d11f612e2bcd977b142dd77ee9857f1d8/traj_opt/trajectory_optimizer.h#L49)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

This one is interesting to document for our convenions.
So if I understand correctly, the expression above is only valid of t=1:num_nodes()? I'd recommend to document that so that we start getting used to sizes and indexes.

Also, what is the size of `q` and `v`? are they the same size? are they of size num_nodes() or num_nodes()+1?
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.cc` line 25 at r2](https://reviewable.io/reviews/vincekurtz/drake/14#-N7qkZ3d-jd26tcke6Ci:-N7rAnNVAd7vz97ZTYev:bmly2p6) ([raw file](https://github.com/vincekurtz/drake/blob/efecb55d11f612e2bcd977b142dd77ee9857f1d8/traj_opt/trajectory_optimizer.cc#L25)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

do we need `v_init`? does it enter into the formulation at all?
</blockquote></details>

Done, resolved per f2f I believe. v_init is used in the computation of tau_0. 
___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 33 at r2](https://reviewable.io/reviews/vincekurtz/drake/14#-N7qnksP6wt0SwaQRUij:-N7rGpSwCXQvKoTGExMz:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/efecb55d11f612e2bcd977b142dd77ee9857f1d8/traj_opt/test/trajectory_optimizer_test.cc#L33)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

This is a very complex way to test `CalcV()`.
Here is a simpler case: consider a constant velocity. Since you are using backward differencing, which is first order, you should at least check that if you provide a linear function `q(t)` you get a constant `v(t)` everywhere. 
</blockquote></details>

Done.
___
*[`traj_opt/examples/pendulum.urdf` line 2 at r2](https://reviewable.io/reviews/vincekurtz/drake/14#-N7qkKsQA7F_EYui-Y9x:-N7rCeQQ82oEA7NNRHZj:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/efecb55d11f612e2bcd977b142dd77ee9857f1d8/traj_opt/examples/pendulum.urdf#L2)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

try to reuse this file if an exact copy of the one in Drake master.
A global search of `pendulum.urdf` reveals it gets used in about 30 places. So there is a way to use it?
</blockquote></details>

Done.

**Review by amcastro-tri — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 11 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/14#-:-N7rXMx0-swJn-ZE2ac1:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @vincekurtz)

___
*[`traj_opt/trajectory_optimizer.h` line 49 at r3](https://reviewable.io/reviews/vincekurtz/drake/14#-N7rWxpb5VcImMa4MzkI:-N7rWxpb5VcImMa4MzkJ:b2s7qp9) ([raw file](https://github.com/vincekurtz/drake/blob/f61203cf45a9dfe09935b941b83b5ee5cdd7a25e/traj_opt/trajectory_optimizer.h#L49)):*
> ```objc
>    *     v_t = (q_t - q_{t-1})/dt            (1)
>    *
>    * v and q are each vectors of length T+1,
> ```

minor, I'd say you say num_steps insteady of T. Is not that you save that much typing anyway and you gain in clarity.

**Pull request merged**
