### PR TITLE
Implements penta-diagonal matrix solver.

### PR DESCRIPTION
**Pull request by amcastro-tri**
First pass. 
I still need to do some minimum cleanup of files names, but the solver already works and passes the units tests.

When we are happy with this first version I'll do a second pass at ensuring there are no heap allocations and I'll push a benchmark just to have an idea how well (or not) this runs.

---
This change is [Reviewable](https://reviewable.io/reviews/vincekurtz/drake/13)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@vincekurtz for feature review please.

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/13#-:-N7blXcg30CJuhZvfK6V:bu9nlwy)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @vincekurtz)

**Review by vincekurtz — CHANGES_REQUESTED** [review]
This looks super awesome! I didn't look into the math in depth, but I trust that you're following the paper and that it works :)

The main thing - would it be possible to merge this into vincekurtz:traj_opt instead of vincekurtz:master? 

I have a PR there (#12) that sets a general outline for things and it would be nice if the structure of this guy fit into that. 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/13#-:-N7bmNFlDEhYXAuRzq2y:b3dd0nw)* status: all files reviewed, 7 unresolved discussions (waiting on @amcastro-tri)

___
*[`multibody/trajopt/BUILD.bazel` line 43 at r1](https://reviewable.io/reviews/vincekurtz/drake/13#-N7bn-as348ahrWCZ1vm:-N7bn-as348ahrWCZ1vn:bt97nkk) ([raw file](https://github.com/vincekurtz/drake/blob/f12e287b0ab49be44e7c0194f0ff5224d1afbd9b/multibody/trajopt/BUILD.bazel#L43)):*
> ```Starlark
> )
> 
> drake_cc_googletest(
> ```

FYI, super helpful to see how this works
___
*[`multibody/trajopt/penta_diagonal_matrix.h` line 12 at r1](https://reviewable.io/reviews/vincekurtz/drake/13#-N7bnzUK-TuIktyCWaD9:-N7bnzUK-TuIktyCWaDA:b3dk645) ([raw file](https://github.com/vincekurtz/drake/blob/f12e287b0ab49be44e7c0194f0ff5224d1afbd9b/multibody/trajopt/penta_diagonal_matrix.h#L12)):*
> ```objc
> namespace trajopt {
> namespace internal {
> ```

Minor, for idiots like me it'd be helpful to a docstring explaining what this thing is and what is looks like. Maybe with a cute little ASCII picture:
```
[ C1 D1 E1  0 0 ]
[ B2 C2 D2 E2 0 ]
[ ...           ]
```
I made such a thing in my other PR (#12) - feel free to copy it
___
*[`multibody/trajopt/penta_diagonal_matrix.cc` line 39 at r1](https://reviewable.io/reviews/vincekurtz/drake/13#-N7bpcPKBANLz3P9IG8n:-N7bpcPKBANLz3P9IG8o:b-c20035) ([raw file](https://github.com/vincekurtz/drake/blob/f12e287b0ab49be44e7c0194f0ff5224d1afbd9b/multibody/trajopt/penta_diagonal_matrix.cc#L39)):*
> ```cpp
>   DRAKE_DEMAND(A_.size() == C_.size());
> 
>   // Alocate space for D and E.
> ```

We could avoid allocating D and E entirely for our symmetric case. It may not end up making too much of a difference, but it's worth noting that the way things are written now, we will have to overwrite the upper triangular part at each iteration. 

We might want to consider a `SymmetricPentaDiagonalMatrix` that inherits from `PentaDiagonalMatrix` and only ever stores `A`, `B`, and `C`. 
___
*[`multibody/trajopt/penta_diagonal_matrix.cc` line 71 at r1](https://reviewable.io/reviews/vincekurtz/drake/13#-N7br2qK8_vFzRSApldY:-N7br2qK8_vFzRSApldZ:b22qclu) ([raw file](https://github.com/vincekurtz/drake/blob/f12e287b0ab49be44e7c0194f0ff5224d1afbd9b/multibody/trajopt/penta_diagonal_matrix.cc#L71)):*
> ```cpp
>   }
> 
>   // Thorough sanity check in debug builds only.
> ```

Minor, ohhh is that the difference between DRAKE_ASSERT and DRAKE_DEMAND? I never understood that before. 

Also, why is this not up with the other size sanity checks?
___
*[`multibody/trajopt/penta_diagonal_matrix.cc` line 71 at r1](https://reviewable.io/reviews/vincekurtz/drake/13#-N7brYK81BlAsrdpQwdw:-N7brYK81BlAsrdpQwdx:b-v5aj7x) ([raw file](https://github.com/vincekurtz/drake/blob/f12e287b0ab49be44e7c0194f0ff5224d1afbd9b/multibody/trajopt/penta_diagonal_matrix.cc#L71)):*
> ```cpp
>   }
> 
>   // Thorough sanity check in debug builds only.
> ```

Might be nice to have a more thorough `VerifySymmetry` check as well for the symmetric case
___
*[`multibody/trajopt/penta_diagonal_solver.h` line 19 at r1](https://reviewable.io/reviews/vincekurtz/drake/13#-N7bvQ6D561ZPe9Yv08d:-N7bvQ6D561ZPe9Yv08e:bs3flg5) ([raw file](https://github.com/vincekurtz/drake/blob/f12e287b0ab49be44e7c0194f0ff5224d1afbd9b/multibody/trajopt/penta_diagonal_solver.h#L19)):*
> ```objc
>   kFailure = 1,
> };
> ```

Probably good practice to reference the paper we're using. Maybe in a docstring here?
___
*[`multibody/trajopt/penta_diagonal_solver.h` line 38 at r1](https://reviewable.io/reviews/vincekurtz/drake/13#-N7bwArV4pobbvQ3i_Uz:-N7bwArV4pobbvQ3i_V-:b-bcekr3) ([raw file](https://github.com/vincekurtz/drake/blob/f12e287b0ab49be44e7c0194f0ff5224d1afbd9b/multibody/trajopt/penta_diagonal_solver.h#L38)):*
> ```objc
> 
>   // Solves M⋅x = b into b. The factorization of M is reused on multiple calls
>   // to this method.
> ```

Will we need a non-in-place solve as well for our problem?
___
*[`multibody/trajopt/test/penta_diagonal_solver_test.cc` line 126 at r1](https://reviewable.io/reviews/vincekurtz/drake/13#-N7bueKeB-Op0YoIt5YQ:-N7bueKeB-Op0YoIt5YR:b-v2c0gj) ([raw file](https://github.com/vincekurtz/drake/blob/f12e287b0ab49be44e7c0194f0ff5224d1afbd9b/multibody/trajopt/test/penta_diagonal_solver_test.cc#L126)):*
> ```cpp
>   EXPECT_EQ(Hchol.status(), PentaDiagonalFactorizationStatus::kSuccess);
>   const VectorXd b = VectorXd::LinSpaced(size, -3, 12.4);
>   VectorXd x = b;
> ```

Minor, would be neat to see some timing comparisons too, but I suppose a unit test is probably the wrong place for that sort of thing

**Review by amcastro-tri — COMMENTED** [review]
Sorry for the lack of docs, I had to run today and didn't get to write any. I'll do a pass sometime this weekend that hopefully will clarify a bunch of your questions.

> would it be possible to merge this into vincekurtz:traj_opt instead of vincekurtz:master?

of course! Since you strated the review here, lets finish first not to loose the history and when done we can close this and push against that banch.

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/13#-:-N7cAtgv-gka6DqzF8hv:b-s2di4t)* status: all files reviewed, 7 unresolved discussions (waiting on @amcastro-tri)

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/13)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @vincekurtz)

___
*[`multibody/trajopt/BUILD.bazel` line 43 at r1](https://reviewable.io/reviews/vincekurtz/drake/13#-N7bn-as348ahrWCZ1vm:-N8VfNuY4_0evNhFv1Rm:b-o4omyl) ([raw file](https://github.com/vincekurtz/drake/blob/f12e287b0ab49be44e7c0194f0ff5224d1afbd9b/multibody/trajopt/BUILD.bazel#L43)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

FYI, super helpful to see how this works
</blockquote></details>

I'm glad!
___
*[`multibody/trajopt/penta_diagonal_matrix.h` line 12 at r1](https://reviewable.io/reviews/vincekurtz/drake/13#-N7bnzUK-TuIktyCWaD9:-N8ENYHx6XJHey9SjAcL:b-yi8bhi) ([raw file](https://github.com/vincekurtz/drake/blob/f12e287b0ab49be44e7c0194f0ff5224d1afbd9b/multibody/trajopt/penta_diagonal_matrix.h#L12)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

Minor, for idiots like me it'd be helpful to a docstring explaining what this thing is and what is looks like. Maybe with a cute little ASCII picture:
```
[ C1 D1 E1  0 0 ]
[ B2 C2 D2 E2 0 ]
[ ...           ]
```
I made such a thing in my other PR (#12) - feel free to copy it
</blockquote></details>

Thanks! that's very neat.
___
*[`multibody/trajopt/penta_diagonal_matrix.cc` line 39 at r1](https://reviewable.io/reviews/vincekurtz/drake/13#-N7bpcPKBANLz3P9IG8n:-N8VdhtZ-ahvj3yVlOp0:bqcjtsv) ([raw file](https://github.com/vincekurtz/drake/blob/f12e287b0ab49be44e7c0194f0ff5224d1afbd9b/multibody/trajopt/penta_diagonal_matrix.cc#L39)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

We could avoid allocating D and E entirely for our symmetric case. It may not end up making too much of a difference, but it's worth noting that the way things are written now, we will have to overwrite the upper triangular part at each iteration. 

We might want to consider a `SymmetricPentaDiagonalMatrix` that inherits from `PentaDiagonalMatrix` and only ever stores `A`, `B`, and `C`. 
</blockquote></details>

I considered that but it turns out that having the copies of the (transposed) diagonals helps quite a bit to simplify the memory layout of the Thomas solver. 
Since this is a private implementation detail and does not affect the contract with the user, I added a TODO for now. Whether we decide to optimize this or not will depend on our benchmarks. 
___
*[`multibody/trajopt/penta_diagonal_matrix.cc` line 71 at r1](https://reviewable.io/reviews/vincekurtz/drake/13#-N7br2qK8_vFzRSApldY:-N8VeRHc6eGQvG-lX4QV:b-hfok4p) ([raw file](https://github.com/vincekurtz/drake/blob/f12e287b0ab49be44e7c0194f0ff5224d1afbd9b/multibody/trajopt/penta_diagonal_matrix.cc#L71)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

Minor, ohhh is that the difference between DRAKE_ASSERT and DRAKE_DEMAND? I never understood that before. 

Also, why is this not up with the other size sanity checks?

</blockquote></details>

Added note.
___
*[`multibody/trajopt/penta_diagonal_matrix.cc` line 71 at r1](https://reviewable.io/reviews/vincekurtz/drake/13#-N7brYK81BlAsrdpQwdw:-N8Vep4iBR5WJucKatMK:bx9j4e2) ([raw file](https://github.com/vincekurtz/drake/blob/f12e287b0ab49be44e7c0194f0ff5224d1afbd9b/multibody/trajopt/penta_diagonal_matrix.cc#L71)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

Might be nice to have a more thorough `VerifySymmetry` check as well for the symmetric case
</blockquote></details>

Actually by construction it is symmetric. It'd be a bug if not. I do have unit tests again dense matrices. 
___
*[`multibody/trajopt/penta_diagonal_solver.h` line 19 at r1](https://reviewable.io/reviews/vincekurtz/drake/13#-N7bvQ6D561ZPe9Yv08d:-N8Vew-P-6CjcQQo-zcH:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/f12e287b0ab49be44e7c0194f0ff5224d1afbd9b/multibody/trajopt/penta_diagonal_solver.h#L19)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

Probably good practice to reference the paper we're using. Maybe in a docstring here?
</blockquote></details>

Done.
___
*[`multibody/trajopt/penta_diagonal_solver.h` line 38 at r1](https://reviewable.io/reviews/vincekurtz/drake/13#-N7bwArV4pobbvQ3i_Uz:-N8Vexd_-EVSMTs241cP:b-8yemo4) ([raw file](https://github.com/vincekurtz/drake/blob/f12e287b0ab49be44e7c0194f0ff5224d1afbd9b/multibody/trajopt/penta_diagonal_solver.h#L38)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

Will we need a non-in-place solve as well for our problem?
</blockquote></details>

maybe? the non-in place is easy to implement from the in-place one anyway.
___
*[`multibody/trajopt/test/penta_diagonal_solver_test.cc` line 126 at r1](https://reviewable.io/reviews/vincekurtz/drake/13#-N7bueKeB-Op0YoIt5YQ:-N8Vf3w5CcWYLa119IFE:b-9aqy57) ([raw file](https://github.com/vincekurtz/drake/blob/f12e287b0ab49be44e7c0194f0ff5224d1afbd9b/multibody/trajopt/test/penta_diagonal_solver_test.cc#L126)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

Minor, would be neat to see some timing comparisons too, but I suppose a unit test is probably the wrong place for that sort of thing
</blockquote></details>

yeah, timing comparisons actually go in a benchmark. Google has a benchmarking suite for that and we do have a few in Drake if we ever want to write one.
I'd wait until we time the whole scheme. Benchmarks are only useful for isolated pieces of code you are interested in optimizing. We still don't know if we'll need to optimize this.

**Review by vincekurtz — APPROVED** [review]
:lgtm: It looks like we can change which branch to merge into from reviewable

> Reviewed 5 of 5 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/13#-:-N8VhHPm2c7yCznDZyMz:b8giazj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amcastro-tri)

**Comment by amcastro-tri** [comment]
nice!

**Pull request merged**
