### PR TITLE
Diagonal scaling of the Hessian

### PR DESCRIPTION
**Pull request by vincekurtz**
Re-scale the Hessian for better conditioning. Uses the re-scaled Hessian `DHD`, where `D = 1/sqrt(diag(H))` is a diagonal scaling matrix. 

This is a rough initial implementation, and includes a bunch of unnecessary heap allocations and dense conversions. 

Builds on #59

- - -
This change is [Reviewable](https://reviewable.io/reviews/vincekurtz/drake/60)

### CODE REVIEW

**Review by vincekurtz — COMMENTED** [review]
+@amcastro-tri for review please! It'll probably be easier to review once we merge #59 

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/60#-:-NI8Of0H8W-opAtFQT3S:bb0m2yi)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @amcastro-tri)

**Review by amcastro-tri — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/60)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @vincekurtz)

___
*[`traj_opt/trajectory_optimizer.h` line 147 at r1](https://reviewable.io/reviews/vincekurtz/drake/60#-NI8QaREA_2d49XFogPJ:-NI8QaREA_2d49XFogPK:b-ahag47) ([raw file](https://github.com/vincekurtz/drake/blob/fcf1d30785e10646510dd3d4a10b4677300f7488/traj_opt/trajectory_optimizer.h#L147)):*
> ```objc
>    */
>   void CalcExactHessian(const TrajectoryOptimizerState<T>& state,
>                         PentaDiagonalMatrix<T>* H) const;
> ```

did you mean to push this in this PR?

**Review by amcastro-tri — COMMENTED** [review]
sounds good, lets merge 59 first.

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/60#-:-NI8Wrky4frHw8HQInsI:bckr3wy)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @vincekurtz)

**Review by amcastro-tri — COMMENTED** [review]
So far so good. Though we are still discussion on Slack whether we like this or not.

> Reviewed 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/60#-:-NIDWcIc11YGbxBdI7dB:bz49bd9)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @vincekurtz)

___
*[`traj_opt/trajectory_optimizer.cc` line 2066 at r2](https://reviewable.io/reviews/vincekurtz/drake/60#-NIDFFg54Lnj-dr749Q8:-NIDFFg54Lnj-dr749Q9:b93ipl2) ([raw file](https://github.com/vincekurtz/drake/blob/a34e89997a641a62052de16a7e1322ee9a5d1919/traj_opt/trajectory_optimizer.cc#L2066)):*
> ```cpp
>   VectorXd g = EvalGradient(state);  // TODO: avoid extra allocations here
>   PentaDiagonalMatrix<double> H = EvalHessian(state);
>   VectorXd D = EvalScaleFactors(state);
> ```

nit, place the Eval inside the `if` below to avoid an unnecessary Calc completely if scaling is not used (now these calcs are expensive).

**Pull request merged**
