### PR TITLE
Compute inverse dynamics as a function of q

### PR DESCRIPTION
**Pull request by vincekurtz**
Computes the inverse dynamics `tau_t(q_{t-1}, q_t, q_{t+1})`. Includes a small unit test based on the simple pendulum. 

Contact/constraints are ignored for now.

---
This change is [Reviewable](https://reviewable.io/reviews/vincekurtz/drake/15)

### CODE REVIEW

**Review by vincekurtz — COMMENTED** [review]
+@amcastro-tri for feature review please

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/15#-:-N7pUpi_4JiiY2X4owNE:brbsdox)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @amcastro-tri)

**Review by amcastro-tri — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/15)* status: 6 of 11 files reviewed, 7 unresolved discussions (waiting on @amcastro-tri and @vincekurtz)

___
*[`traj_opt/problem_definition.h` line 2 at r1](https://reviewable.io/reviews/vincekurtz/drake/15#-N7qrAgi1qMoMcIHnwT7:-N7qrAgjB6ZRj5JDdVgg:b-j4em3q) ([raw file](https://github.com/vincekurtz/drake/blob/4b0a1e096819e455a2d15f6393d7aeb372a7d326/traj_opt/problem_definition.h#L2)):*
> ```objc
> #pragma once
> ```

file being reviewed in #14.
___
*[`traj_opt/trajectory_optimizer.h` line 74 at r1](https://reviewable.io/reviews/vincekurtz/drake/15#-N7qrhA1-0Rg9J1_wtFT:-N7qrhA1-0Rg9J1_wtFU:bifajhf) ([raw file](https://github.com/vincekurtz/drake/blob/4b0a1e096819e455a2d15f6393d7aeb372a7d326/traj_opt/trajectory_optimizer.h#L74)):*
> ```objc
>    * @param q sequence of generalized positions
>    * @param v sequence of generalized velocities
>    * @param tau sequence of generalized forces
> ```

document sizes. Per #14 q and v seem to have size num_steps+1. 
per f2f, document that our convention is that tau has size num_steps so that tau_t are the generalized forces that take us from t to t+1.
___
*[`traj_opt/trajectory_optimizer.cc` line 56 at r1](https://reviewable.io/reviews/vincekurtz/drake/15#-N7qwd611OBY1usa0vXN:-N7qwd611OBY1usa0vXO:bl6drma) ([raw file](https://github.com/vincekurtz/drake/blob/4b0a1e096819e455a2d15f6393d7aeb372a7d326/traj_opt/trajectory_optimizer.cc#L56)):*
> ```cpp
> 
>   const int nv = plant().num_velocities();
>   VectorXd a(nv);                          // acceleration
> ```

I'd pass in `a` and `f_ext` from the outside as "scratch space" so that we minimize heap allocations. This will get called a lot, and more so with finite differences, so minimizing heap allocations will pay off a bit.
___
*[`traj_opt/trajectory_optimizer.cc` line 58 at r1](https://reviewable.io/reviews/vincekurtz/drake/15#-N7qwWt1DaaxvAghUd3a:-N7qwWt1DaaxvAghUd3b:b-1vcnc7) ([raw file](https://github.com/vincekurtz/drake/blob/4b0a1e096819e455a2d15f6393d7aeb372a7d326/traj_opt/trajectory_optimizer.cc#L58)):*
> ```cpp
>   VectorXd a(nv);                          // acceleration
>   MultibodyForces<double> f_ext(plant());  // external forces
>   VectorXd tau_id(nv);                     // inverse dynamics
> ```

I don't think you need `tau_id`? you can write everything into `tau`.
___
*[`traj_opt/trajectory_optimizer.cc` line 67 at r1](https://reviewable.io/reviews/vincekurtz/drake/15#-N7qvtQQ240vAmNwY5zJ:-N7qvtQQ240vAmNwY5zK:b6gjg6o) ([raw file](https://github.com/vincekurtz/drake/blob/4b0a1e096819e455a2d15f6393d7aeb372a7d326/traj_opt/trajectory_optimizer.cc#L67)):*
> ```cpp
>     plant().CalcForceElementsContribution(*context_, &f_ext);
> 
>     // Inverse dynamics computes M*a + D*v + C(q,v)v + f_ext
> ```

nit, in our notation k(q,v) contains both Coriolis and other force elements such as gravity (for a shorter equation)
___
*[`traj_opt/trajectory_optimizer.cc` line 72 at r1](https://reviewable.io/reviews/vincekurtz/drake/15#-N7qwHtkCjHQXdt-eXsA:-N7qwHtl0hizFwSHQ2wY:b253qbb) ([raw file](https://github.com/vincekurtz/drake/blob/4b0a1e096819e455a2d15f6393d7aeb372a7d326/traj_opt/trajectory_optimizer.cc#L72)):*
> ```cpp
>     // CalcInverseDynamics considers damping from v_t (D*v_t), but we want to
>     // consider damping from v_{t+1} (D*v_{t+1}).
>     damping_correction = joint_damping_.array() * (v[t+1].array() - v[t].array());
> ```

here you might want to do `tau->array() += joint_damping_.array() * (v[t+1].array() - v[t].array());` to minimize the number of heap allocations (expensive inside inner loops).
___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 68 at r1](https://reviewable.io/reviews/vincekurtz/drake/15#-N7qxPQA2q8ww--4GupO:-N7qxPQA2q8ww--4GupP:bsgixyy) ([raw file](https://github.com/vincekurtz/drake/blob/4b0a1e096819e455a2d15f6393d7aeb372a7d326/traj_opt/test/trajectory_optimizer_test.cc#L68)):*
> ```cpp
>   std::vector<VectorXd> q;
>   for (int t = 0; t <= num_steps; ++t) {
>     q.emplace_back(x.block<1, 1>(0, t));
> ```

minor, a bit awkward when here you can simply say x(0, t)

**Review by amcastro-tri — COMMENTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/15)* status: 7 of 11 files reviewed, 7 unresolved discussions (waiting on @amcastro-tri and @vincekurtz)

**Review by vincekurtz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/15)* status: 4 of 11 files reviewed, 5 unresolved discussions (waiting on @amcastro-tri)

___
*[`traj_opt/problem_definition.h` line 2 at r1](https://reviewable.io/reviews/vincekurtz/drake/15#-N7qrAgi1qMoMcIHnwT7:-N7rTHdw2WlkCdHQ61ii:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/4b0a1e096819e455a2d15f6393d7aeb372a7d326/traj_opt/problem_definition.h#L2)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

file being reviewed in #14.
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.h` line 74 at r1](https://reviewable.io/reviews/vincekurtz/drake/15#-N7qrhA1-0Rg9J1_wtFT:-N7rKYeQB9jIIhIbHP2N:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/4b0a1e096819e455a2d15f6393d7aeb372a7d326/traj_opt/trajectory_optimizer.h#L74)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

document sizes. Per #14 q and v seem to have size num_steps+1. 
per f2f, document that our convention is that tau has size num_steps so that tau_t are the generalized forces that take us from t to t+1.
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.cc` line 56 at r1](https://reviewable.io/reviews/vincekurtz/drake/15#-N7qwd611OBY1usa0vXN:-N7rRjRr4mB19CFKw5aj:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/4b0a1e096819e455a2d15f6393d7aeb372a7d326/traj_opt/trajectory_optimizer.cc#L56)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I'd pass in `a` and `f_ext` from the outside as "scratch space" so that we minimize heap allocations. This will get called a lot, and more so with finite differences, so minimizing heap allocations will pay off a bit.
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.cc` line 58 at r1](https://reviewable.io/reviews/vincekurtz/drake/15#-N7qwWt1DaaxvAghUd3a:-N7rMiTk9kNsKtSIELQ6:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/4b0a1e096819e455a2d15f6393d7aeb372a7d326/traj_opt/trajectory_optimizer.cc#L58)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I don't think you need `tau_id`? you can write everything into `tau`.
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.cc` line 72 at r1](https://reviewable.io/reviews/vincekurtz/drake/15#-N7qwHtkCjHQXdt-eXsA:-N7rMgBVCamWDpqCY1oW:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/4b0a1e096819e455a2d15f6393d7aeb372a7d326/traj_opt/trajectory_optimizer.cc#L72)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

here you might want to do `tau->array() += joint_damping_.array() * (v[t+1].array() - v[t].array());` to minimize the number of heap allocations (expensive inside inner loops).
</blockquote></details>

Done.

**Review by amcastro-tri — CHANGES_REQUESTED** [review]
:lgtm: , I can show you tomorrow how to write a unit test that verifies we do not allocate.
If you are interested tonight, do a search for `LimitMalloc` in Drake.

> Reviewed 4 of 11 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/15#-:-N7rYChNCebXLEIKS39g:b-5o5izx)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @vincekurtz)

___
*[`traj_opt/trajectory_optimizer.cc` line 62 at r2](https://reviewable.io/reviews/vincekurtz/drake/15#-N7rXhywDFbyhaAl8mME:-N7rXhyxENTJ2AQFvOvD:b-qa553r) ([raw file](https://github.com/vincekurtz/drake/blob/94fafbccd01e7fa6c55231896c69e0ed1bf36fdb/traj_opt/trajectory_optimizer.cc#L62)):*
> ```cpp
>     // Inverse dynamics computes M*a + D*v - k(q,v)
>     tau->at(t) = plant().CalcInverseDynamics(
>         *context_, (v[t + 1] - v[t]) / time_step(), *f_ext);
> ```

fyi , c++ creates a temporary right here to store the result of this inline computation. That is, the compiler needs to place this somewhere before passing it down to this function.
To avoid this, the easiest is to pass a `VectorXd* a_scratch` as you did with the forces.
___
*[`traj_opt/examples/pendulum.urdf` line 1 at r2](https://reviewable.io/reviews/vincekurtz/drake/15#-N7rY88k0O8L_zrB6qvm:-N7rY88k0O8L_zrB6qvn:b-f8qa8m) ([raw file](https://github.com/vincekurtz/drake/blob/94fafbccd01e7fa6c55231896c69e0ed1bf36fdb/traj_opt/examples/pendulum.urdf#L1)):*
> ```XML
> <?xml version="1.0"?>
> ```

reuse file from mater

**Review by vincekurtz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/15)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @amcastro-tri)

___
*[`traj_opt/examples/pendulum.urdf` line 1 at r2](https://reviewable.io/reviews/vincekurtz/drake/15#-N7rY88k0O8L_zrB6qvm:-N7uuobVE3riN5kJNZFs:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/94fafbccd01e7fa6c55231896c69e0ed1bf36fdb/traj_opt/examples/pendulum.urdf#L1)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

reuse file from mater
</blockquote></details>

Done.

**Pull request merged**
