### PR TITLE
Compute the Hessian

### PR DESCRIPTION
**Pull request by vincekurtz**
Calculates our Gauss-Newton approximation of the Hessian of the unconstrained cost. 

Adds unit tests (pendulum and acrobot) based on computing the (true) Hessian with autodiff. For the simple pendulum, our Gauss-Newton approximation is quite close to the true Hessian. For the acrobot, it's more of a rough approximation.

---
This change is [Reviewable](https://reviewable.io/reviews/vincekurtz/drake/23)

### CODE REVIEW

**Review by vincekurtz — COMMENTED** [review]
+@amcastro-tri for feature review please

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/23#-:-N8UajFECNLhdLoQDOUj:brbsdox)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @amcastro-tri)

**Review by vincekurtz — COMMENTED** [review]
This is using sparse algebra now, not dense. But I'm not sure if I can change the name of the PR at this point. 

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/23#-:-N8Z_pQU2HmZCiGZfDmd:b-d6lpew)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @amcastro-tri)

**Review by amcastro-tri — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/23#-:-N8_EQeM1Lo9rhqVaj5f:bg7igkv)* status: all files reviewed, 15 unresolved discussions (waiting on @vincekurtz)

___
*[`traj_opt/penta_diagonal_matrix.cc` line 60 at r3](https://reviewable.io/reviews/vincekurtz/drake/23#-N8_7ntZ9qp63aVxyqwO:-N8_7ntZ9qp63aVxyqwP:brm4h0b) ([raw file](https://github.com/vincekurtz/drake/blob/3bd9c61a5ceca5fcc230822456eea2eca5789c5b/traj_opt/penta_diagonal_matrix.cc#L60)):*
> ```cpp
> 
>   // Copy the lower triangular part to the upper triangular part.
>   MakeSymmetric();
> ```

btw, nice reuse of code
___
*[`traj_opt/trajectory_optimizer.h` line 108 at r3](https://reviewable.io/reviews/vincekurtz/drake/23#-N8_BRL_2Ml9NoWq7pwD:-N8_BRL_2Ml9NoWq7pwE:b-8mu9i1) ([raw file](https://github.com/vincekurtz/drake/blob/3bd9c61a5ceca5fcc230822456eea2eca5789c5b/traj_opt/trajectory_optimizer.h#L108)):*
> ```objc
>    * @param state optimizer state, including q, v, tau, gradients, etc.
>    * @param H a PentaDiagonalMatrix containing the second-order derivatives of
>    *          the total cost L(q).
> ```

minor, document H size, I always need to think twice about it :-/
___
*[`traj_opt/trajectory_optimizer.cc` line 394 at r3](https://reviewable.io/reviews/vincekurtz/drake/23#-N8_BI_G2n2plnYe9QM_:-N8_BI_G2n2plnYe9QMa:b-629fvo) ([raw file](https://github.com/vincekurtz/drake/blob/3bd9c61a5ceca5fcc230822456eea2eca5789c5b/traj_opt/trajectory_optimizer.cc#L394)):*
> ```cpp
> void TrajectoryOptimizer<T>::CalcHessian(
>     const TrajectoryOptimizerState<T>& state, PentaDiagonalMatrix<T>* H) const {
>   DRAKE_DEMAND(H->is_symmetric());
> ```

nit, maybe DEMAND proper size of H?
___
*[`traj_opt/trajectory_optimizer.cc` line 402 at r3](https://reviewable.io/reviews/vincekurtz/drake/23#-N8_8N8H2lAmql8mZrck:-N8_8N8H2lAmql8mZrcl:b-9yqs3u) ([raw file](https://github.com/vincekurtz/drake/blob/3bd9c61a5ceca5fcc230822456eea2eca5789c5b/traj_opt/trajectory_optimizer.cc#L402)):*
> ```cpp
>   // Some convienient aliases
>   const double dt = time_step();
>   const MatrixX<T>& Qq = 2 * prob_.Qq * dt;
> ```

the `&` here does not do what you think. The right hand side is computing something and therefore a new object (a place in memory) must be created. So this line is creating a new object and you are getting a reference to that new object.

Bottom line, here you inevitable need to write `const MatrixX<T>`, without `&`.
___
*[`traj_opt/trajectory_optimizer.cc` line 419 at r3](https://reviewable.io/reviews/vincekurtz/drake/23#-N8_93uDCdqtBL5Jsc-E:-N8_93uDCdqtBL5Jsc-F:bvi2fmr) ([raw file](https://github.com/vincekurtz/drake/blob/3bd9c61a5ceca5fcc230822456eea2eca5789c5b/traj_opt/trajectory_optimizer.cc#L419)):*
> ```cpp
> 
>   // Fill in the non-zero blocks
>   C[0].setIdentity();
> ```

minor, consider to add inline comment like `// Initial condition at t = 0.`, or similar.
___
*[`traj_opt/trajectory_optimizer.cc` line 422 at r3](https://reviewable.io/reviews/vincekurtz/drake/23#-N8_9GRq-Z7ntPmS1zZ_:-N8_9GRq-Z7ntPmS1zZa:bek7yk9) ([raw file](https://github.com/vincekurtz/drake/blob/3bd9c61a5ceca5fcc230822456eea2eca5789c5b/traj_opt/trajectory_optimizer.cc#L422)):*
> ```cpp
>   for (int t = 1; t < num_steps(); ++t) {
>     // dg_t/dq_t
>     Eigen::Ref<MatrixX<T>> dgt_dqt = C[t];
> ```

no need for `Eigen::Ref`? you can simply do `MatrixX<T>& dgt_dqt = C[t]`
___
*[`traj_opt/trajectory_optimizer.cc` line 431 at r3](https://reviewable.io/reviews/vincekurtz/drake/23#-N8_AMwj86HilznREajm:-N8_AMwk41ZDwkFkmNGy:br8iw6k) ([raw file](https://github.com/vincekurtz/drake/blob/3bd9c61a5ceca5fcc230822456eea2eca5789c5b/traj_opt/trajectory_optimizer.cc#L431)):*
> ```cpp
>       dgt_dqt += dvt_dqm[t + 1].transpose() * Qv * dvt_dqm[t + 1];
>     } else {
>       dgt_dqt += dvt_dqm[t + 1].transpose() * Qf_v * dvt_dqm[t + 1];
> ```

this only happens for `t+1 = num_steps() - 1`.
So maybe for clarity maybe move outside the loop in the section you documented below as "Terminal cost"?
___
*[`traj_opt/trajectory_optimizer.cc` line 435 at r3](https://reviewable.io/reviews/vincekurtz/drake/23#-N8_AmMKAWKxgNHwn_20:-N8_AmMKAWKxgNHwn_21:b-60vu0u) ([raw file](https://github.com/vincekurtz/drake/blob/3bd9c61a5ceca5fcc230822456eea2eca5789c5b/traj_opt/trajectory_optimizer.cc#L435)):*
> ```cpp
> 
>     // dg_t/dq_{t+1}
>     Eigen::Ref<MatrixX<T>> dgt_dqp = B[t + 1];
> ```

ditto Eigen::Ref
___
*[`traj_opt/trajectory_optimizer.cc` line 441 at r3](https://reviewable.io/reviews/vincekurtz/drake/23#-N8_AgqQ11enQgL3PlWc:-N8_AgqQ11enQgL3PlWd:bsjofpc) ([raw file](https://github.com/vincekurtz/drake/blob/3bd9c61a5ceca5fcc230822456eea2eca5789c5b/traj_opt/trajectory_optimizer.cc#L441)):*
> ```cpp
>       dgt_dqp += dvt_dqt[t + 1].transpose() * Qv * dvt_dqm[t + 1];
>     } else {
>       dgt_dqp += dvt_dqt[t + 1].transpose() * Qf_v * dvt_dqm[t + 1];
> ```

ditto, move to "Terminal cost" section of code?
___
*[`traj_opt/trajectory_optimizer.cc` line 446 at r3](https://reviewable.io/reviews/vincekurtz/drake/23#-N8_Ao629xxkVUU65VKe:-N8_Ao629xxkVUU65VKf:b-98g6iz) ([raw file](https://github.com/vincekurtz/drake/blob/3bd9c61a5ceca5fcc230822456eea2eca5789c5b/traj_opt/trajectory_optimizer.cc#L446)):*
> ```cpp
>     // dg_t/dq_{t+2}
>     if (t < num_steps() - 1) {
>       Eigen::Ref<MatrixX<T>> dgt_dqpp = A[t + 2];
> ```

and ditto Eigen::Ref and "Terminal Cost"
___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 94 at r3](https://reviewable.io/reviews/vincekurtz/drake/23#-N8_Bj1FEOHDJjgujnaO:-N8_Bj1FEOHDJjgujnaP:bi0lxd3) ([raw file](https://github.com/vincekurtz/drake/blob/3bd9c61a5ceca5fcc230822456eea2eca5789c5b/traj_opt/test/trajectory_optimizer_test.cc#L94)):*
> ```cpp
>   opt_prob.q_init = Vector2d(0.1, 0.2);
>   opt_prob.v_init = Vector2d(-0.01, 0.03);
>   opt_prob.Qq = 0.1 * MatrixXd::Identity(2, 2);
> ```

minor, optimization I realize we can do, TODO suffices in the corresponding file.
I imagine these will always be diagonal matrices. Therefore you can only store the diagonal as a `VectorX`.
Eigen has a nice method `asDiagonal()` so that if `d` is the diagonal of diagonal matrix `D`, then `D*x` is written as `d.asDiagonal() * x`.
___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 96 at r3](https://reviewable.io/reviews/vincekurtz/drake/23#-N8_B_EyDE4pFmHLIwQf:-N8_B_EyDE4pFmHLIwQg:b-im19v3) ([raw file](https://github.com/vincekurtz/drake/blob/3bd9c61a5ceca5fcc230822456eea2eca5789c5b/traj_opt/test/trajectory_optimizer_test.cc#L96)):*
> ```cpp
>   opt_prob.Qq = 0.1 * MatrixXd::Identity(2, 2);
>   opt_prob.Qv = 0.0 * MatrixXd::Identity(2, 2);
>   opt_prob.Qf_q = 0.0 * MatrixXd::Identity(2, 2);
> ```

nit, maybe for testing purposes make these non-zero to make sure they propagate through the computation accordingly?
___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 121 at r3](https://reviewable.io/reviews/vincekurtz/drake/23#-N8_CHAj7HBVB8yuV-yG:-N8_CHAj7HBVB8yuV-yH:b1wjzes) ([raw file](https://github.com/vincekurtz/drake/blob/3bd9c61a5ceca5fcc230822456eea2eca5789c5b/traj_opt/test/trajectory_optimizer_test.cc#L121)):*
> ```cpp
>   state.set_q(q);
> 
>   // Compute the Gauss-Newton Hessian approximation analytically
> ```

minor, "numerically"?



_Code quote:_
```cpp
 analytically
```
___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 128 at r3](https://reviewable.io/reviews/vincekurtz/drake/23#-N8_CL0h9944ZUI3Z_xJ:-N8_CL0h9944ZUI3Z_xK:b-wxixm) ([raw file](https://github.com/vincekurtz/drake/blob/3bd9c61a5ceca5fcc230822456eea2eca5789c5b/traj_opt/test/trajectory_optimizer_test.cc#L128)):*
> ```cpp
>   MatrixXd H = H_sparse.MakeDense();
> 
>   // Set up an autodiff copy of the optimizer and plant
> ```

minor, here yes, analytically. 
___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 149 at r3](https://reviewable.io/reviews/vincekurtz/drake/23#-N8_EFRl6o-65XCtw2Zi:-N8_EFRm3AhFKs-9eoYF:b-i6u568) ([raw file](https://github.com/vincekurtz/drake/blob/3bd9c61a5ceca5fcc230822456eea2eca5789c5b/traj_opt/test/trajectory_optimizer_test.cc#L149)):*
> ```cpp
>   //
>   //    L(q) = 1/2 r(q)'*r(q)
>   //    J = dr(q)/dq
> ```

btw, I imagine this will be handy to have around when we introduce contact, for testing. 
Maybe consider making this a helper of the optimizer? another PR is ok.
___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 155 at r3](https://reviewable.io/reviews/vincekurtz/drake/23#-N8_CXG9AwSJdHW_aBOG:-N8_CXG9AwSJdHW_aBOH:b-y3kr89) ([raw file](https://github.com/vincekurtz/drake/blob/3bd9c61a5ceca5fcc230822456eea2eca5789c5b/traj_opt/test/trajectory_optimizer_test.cc#L155)):*
> ```cpp
>   //    g = J'r,
>   //    H = J'J.
>   //
> ```

very nice! consider adding the definition for `r(q)` in this comment to make it complete.
___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 165 at r3](https://reviewable.io/reviews/vincekurtz/drake/23#-N8_CrZnD8y607mRyBri:-N8_CrZnD8y607mRyBrj:b4qmsvl) ([raw file](https://github.com/vincekurtz/drake/blob/3bd9c61a5ceca5fcc230822456eea2eca5789c5b/traj_opt/test/trajectory_optimizer_test.cc#L165)):*
> ```cpp
>   const std::vector<VectorX<AutoDiffXd>>& u_ad = state_ad.cache().tau;
> 
>   VectorX<AutoDiffXd> r(num_steps * 6 + 4);
> ```

nit, consider either documenting or naming these constants so it's clear where they come from.

**Review by amcastro-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/23)* status: 4 of 9 files reviewed, 16 unresolved discussions

___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 168 at r4](https://reviewable.io/reviews/vincekurtz/drake/23#-N8__7kd9t9bq3IU1SSN:-N8__7ke2Mp2q3j1eBmR:b-7kxvfd) ([raw file](https://github.com/vincekurtz/drake/blob/702b4a47b2dbe57caf48fe64920bd5a0649eff8c/traj_opt/test/trajectory_optimizer_test.cc#L168)):*
> ```cpp
>   //        [        ...           ]
>   //        [ sqrt(Qq)*(q_t-q_nom) ]
>   // r(q) = [ sqrt(Qv)*(v_t-v_nom) ]
> ```

fyi, this comment is missing the `sqrt(2*dt)` factor.
___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 170 at r4](https://reviewable.io/reviews/vincekurtz/drake/23#-N8__CPJ5REcbcRXZlvr:-N8__CPJ5REcbcRXZlvs:b-usdb9b) ([raw file](https://github.com/vincekurtz/drake/blob/702b4a47b2dbe57caf48fe64920bd5a0649eff8c/traj_opt/test/trajectory_optimizer_test.cc#L170)):*
> ```cpp
>   // r(q) = [ sqrt(Qv)*(v_t-v_nom) ]
>   //        [ sqrt(R) * tau_t      ]
>   //        [        ...           ]
> ```

are the `...` needed here? maybe if you write `sqrt(R)*tau` not needed?

**Pull request merged**
