### PR TITLE
Add TrajectoryOptimizerState and refactor accordingly

### PR DESCRIPTION
**Pull request by vincekurtz**
This is a non-functional re-organization of some code to improve clarity moving forward. 

Primary changes:
- Adding `TrajectoryOptimizerState` to hold a sequence of generalized positions `q`, and `TrajectoryOptimizerCache` to hold stuff that is computed from `q`, like velocities, accelerations, inverse dynamics, etc. 
- All of the computations related to the `TrajectoryOptimizerCache` are performed once by an `UpdateState` function
- Adopting a more explicit & consistent naming scheme: `CalcVelocities`, `CalcAccelerations`, and `CalcInverseDynamics` now refer to computations over the whole trajectory. Similarly, `CalcInverseDynamicsPartials` considers the whole trajectory. `CalcInverseDynamicsSingleTimeStep` computes inverse dynamics for one time step.
- `GradientData` is renamed `InverseDynamicsPartials` and only stores `d(tau)/d(q)`. 
- `d(v)/d(q)` is now stored in a new `VelocityPartials` object
- `TrajectoryOptimizer` now has methods to construct a `TrajectoryOptimizerState` and a `TrajectoryOptimizerWorkspace`

---
This change is [Reviewable](https://reviewable.io/reviews/vincekurtz/drake/21)

### CODE REVIEW

**Review by vincekurtz — COMMENTED** [review]
+@amcastro-tri for feature review please

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/21#-:-N8OWVDm5FZKMhqEImcu:brbsdox)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @amcastro-tri)

**Review by amcastro-tri — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/21)* status: 3 of 5 files reviewed, 11 unresolved discussions (waiting on @amcastro-tri and @vincekurtz)

*[a discussion](https://reviewable.io/reviews/vincekurtz/drake/21#-N8OmcfX-8OraJ-TP3IP:-N8OmcfX-8OraJ-TP3IQ:bd4hs8v) (no related file):*
Random question. Have you been rebasing regularly on top of Drake master? 
We wanna make sure we are not that out of date.

___
___
*[`traj_opt/problem_data.h` line 21 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8OnXTO0GtlgjSR4rFy:-N8OnXTO0GtlgjSR4rFz:bq1oqy1) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/problem_data.h#L21)):*
> ```objc
>  */
> struct VelocityPartials {
>   double dvt_dqt;
> ```

this essentially is either 1 or -1.
For when we introduce N+ (we will) this will be a function of `q` and and you'll need to somehow store it.
Not sure how that'd work with this struct. 
I'd probably would not introduce this concept until you actually use it and see how it fits together. If I understand correctly, I believe you won't even need this.
___
*[`traj_opt/problem_data.h` line 147 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8OnwGhEReZMvVNgdmX:-N8OnwGhEReZMvVNgdmY:bn9wf8a) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/problem_data.h#L147)):*
> ```objc
>   // for our calculations
>   TrajectoryOptimizerCache cache;
> };
> ```

weird, I haven't seen the rest, but I would've thought you'd want this guy to be `mutable` (C++ keyword mutable). 
I'll keep looking...
___
*[`traj_opt/trajectory_optimizer.h` line 63 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8OpLGE83bx-VtfHKxS:-N8OpLGFAajNon8rNUbW:b-drwmt7) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/trajectory_optimizer.h#L63)):*
> ```objc
>    * @return TrajectoryOptimizerState
>    */
>   TrajectoryOptimizerState ConstructState() const {
> ```

minor, in Drake we use either `Create` or `Make`. 
`Construct` is ok if you like it. It just so happens it's a bit odd to overload this C++ term. For reference, the STL likes to use `make`, which I believe it's where we stole term from.
___
*[`traj_opt/trajectory_optimizer.h` line 73 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8Opk40DKi2FQz0UtIT:-N8Opk417XGt8iGWZE2V:bveuq2) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/trajectory_optimizer.h#L73)):*
> ```objc
>    * @return TrajectoryOptimizerWorkspace
>    */
>   TrajectoryOptimizerWorkspace ConstructWorkspace() const {
> ```

I believe this should be private? only the optimizer, not the user, can call it.

Side note, I think it is OK to place this scratch space in your state as well. We actually do that in Drake!
___
*[`traj_opt/trajectory_optimizer.h` line 103 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8Oq-nsEVeDM2SzCY4L:-N8Oq-nsEVeDM2SzCY4M:b-lvv8m) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/trajectory_optimizer.h#L103)):*
> ```objc
>   double CalcCost(const std::vector<VectorXd>& q,
>                   const std::vector<VectorXd>& v,
>                   const std::vector<VectorXd>& tau,
> ```

Strange to see these public.
I believe the "user-facing" APIs you want are of the form `FooResult CalcFoo(const TrajectoryOptimizerState& state)` or also `void CalcFoo(const TrajectoryOptimizerState& state, FooResult* result)`
___
*[`traj_opt/trajectory_optimizer.h` line 133 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8OqS2f6rtoDoSJuVZj:-N8OqS2f6rtoDoSJuVZk:bi9hbl7) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/trajectory_optimizer.h#L133)):*
> ```objc
>    * @param v sequence of generalized velocities
>    */
>   void CalcVelocities(const std::vector<VectorXd>& q,
> ```

btw, nice! I like this name much better!
and btw, make private if only a helper for the optimizer.
___
*[`traj_opt/trajectory_optimizer.h` line 188 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8Os03P5BKQbscy0mDt:-N8Os03P5BKQbscy0mDu:b-pfkcth) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/trajectory_optimizer.h#L188)):*
> ```objc
>    * Compute the gradient of the unconstrained cost L(q).
>    *
>    * @param state optimizer state, including q, v, tau, gradients, etc.
> ```

if you are going to be checking that `state` is properly up to date, then at least document here that precondition. 
___
*[`traj_opt/trajectory_optimizer.h` line 196 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8Oqboq-UeK5nxQuy78:-N8Oqboq-UeK5nxQuy79:bfpb3wi) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/trajectory_optimizer.h#L196)):*
> ```objc
>                     TrajectoryOptimizerWorkspace* workspace,
>                     EigenPtr<VectorXd> g) const;
> ```

nice! I love how this reads. Great for a public API.
now, you might consider placing the workspace also in the state for an even simpler API.
___
*[`traj_opt/trajectory_optimizer.h` line 245 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8OqnrH7F9aTN4BdYmt:-N8OqnrH7F9aTN4BdYmu:b-5dixub) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/trajectory_optimizer.h#L245)):*
> ```objc
>    * @param v_partials struct for holding dv/dq
>    */
>   void CalcVelocityPartials(const std::vector<VectorXd>& q,
> ```

I don't think we'll want to compute this and also..... we don't even need them? 
The way we are doing things is to compute velocities from qs. Now, currently you are computing qdot instead. Computing velocities is easy! you simply do `plant_->MapQDotToVelocity(context_with_q, qdot, &v)`. So no need to build N+.
___
*[`traj_opt/trajectory_optimizer.h` line 280 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8OrVXj2jdzGCbSLRRm:-N8OrVXkA4fI6Nw91G6F:b1shytu) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/trajectory_optimizer.h#L280)):*
> ```objc
>    */
>   void CalcInverseDynamicsPartialsFiniteDiff(
>       const std::vector<VectorXd>& q, const std::vector<VectorXd>& v,
> ```

I like these are private. Why wouldn't the methods above in the public section be private as well?
___
*[`traj_opt/trajectory_optimizer_workspace.h` line 44 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8OoMlJ7yDlSofT-nGm:-N8OoMlK9E4ftmIFm7Lx:b-n7m69h) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/trajectory_optimizer_workspace.h#L44)):*
> ```objc
>     for (int t = 0; t <= num_steps; ++t) {
>       q_sequence_tmp1.push_back(VectorXd(nq));
>       q_sequence_tmp2.push_back(VectorXd(nq));
> ```

nit, strange to see here you didn't use your `.assign(num_steps, VectorXd(nq)` trick?

**Review by vincekurtz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/21)* status: 0 of 9 files reviewed, 10 unresolved discussions (waiting on @amcastro-tri)

*[a discussion](https://reviewable.io/reviews/vincekurtz/drake/21#-N8OmcfX-8OraJ-TP3IP:-N8OvlZqCp1T43Xkghrm:bq5nys2) (no related file):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Random question. Have you been rebasing regularly on top of Drake master? 
We wanna make sure we are not that out of date.
</blockquote></details>

I rebased on Thursday, I believe, and can do so again today once this lands. 

___
___
*[`traj_opt/problem_data.h` line 21 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8OnXTO0GtlgjSR4rFy:-N8OvyLF2RfbuZbHbduO:b-m1bmmb) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/problem_data.h#L21)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

this essentially is either 1 or -1.
For when we introduce N+ (we will) this will be a function of `q` and and you'll need to somehow store it.
Not sure how that'd work with this struct. 
I'd probably would not introduce this concept until you actually use it and see how it fits together. If I understand correctly, I believe you won't even need this.
</blockquote></details>

Per f2f, changing this to 
```
std::vector<MatrixXd> dvt_dqt
std::vector<MatrixXd> dvt_dqm
```
where `dvt_dqt[t]` stores N+(q_t).

In the future, instead of storing N+(q_t) as a matrix, we can consider some fancy operator that allows us to multiply by N+(q_t). 
___
*[`traj_opt/problem_data.h` line 147 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8OnwGhEReZMvVNgdmX:-N8P1b9514USjtGGeUMd:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/problem_data.h#L147)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

weird, I haven't seen the rest, but I would've thought you'd want this guy to be `mutable` (C++ keyword mutable). 
I'll keep looking...
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.h` line 63 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8OpLGE83bx-VtfHKxS:-N8P31xa9NlmSGkzFfWe:buyh162) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/trajectory_optimizer.h#L63)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

minor, in Drake we use either `Create` or `Make`. 
`Construct` is ok if you like it. It just so happens it's a bit odd to overload this C++ term. For reference, the STL likes to use `make`, which I believe it's where we stole term from.
</blockquote></details>

Makes sense, I'll go with `Create` here
___
*[`traj_opt/trajectory_optimizer.h` line 73 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8Opk40DKi2FQz0UtIT:-N8Q7CPXEgk8SNKD0L0z:b-n954ya) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/trajectory_optimizer.h#L73)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I believe this should be private? only the optimizer, not the user, can call it.

Side note, I think it is OK to place this scratch space in your state as well. We actually do that in Drake!
</blockquote></details>

I put it in the `TrajectoryOptimizerState` and removed this function entirely
___
*[`traj_opt/trajectory_optimizer.h` line 103 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8Oq-nsEVeDM2SzCY4L:-N8OxZlt3KCU3kZqrPvD:bb6un1j) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/trajectory_optimizer.h#L103)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Strange to see these public.
I believe the "user-facing" APIs you want are of the form `FooResult CalcFoo(const TrajectoryOptimizerState& state)` or also `void CalcFoo(const TrajectoryOptimizerState& state, FooResult* result)`
</blockquote></details>

Done
___
*[`traj_opt/trajectory_optimizer.h` line 188 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8Os03P5BKQbscy0mDt:-N8Q7RuI3rIygQDAk2_8:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/trajectory_optimizer.h#L188)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

if you are going to be checking that `state` is properly up to date, then at least document here that precondition. 
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.h` line 196 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8Oqboq-UeK5nxQuy78:-N8Q7TouAM5SN0zHnw3I:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/trajectory_optimizer.h#L196)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

nice! I love how this reads. Great for a public API.
now, you might consider placing the workspace also in the state for an even simpler API.
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer.h` line 245 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8OqnrH7F9aTN4BdYmt:-N8OyE2H0uwMkQFda_iO:bqu0sq7) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/trajectory_optimizer.h#L245)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I don't think we'll want to compute this and also..... we don't even need them? 
The way we are doing things is to compute velocities from qs. Now, currently you are computing qdot instead. Computing velocities is easy! you simply do `plant_->MapQDotToVelocity(context_with_q, qdot, &v)`. So no need to build N+.
</blockquote></details>

In the Hessian we have terms like `[d(v_t)/d(q_{t-1})]' * Q * d(v_t)/d(q_t)`. Can we still get away with not building N+?
___
*[`traj_opt/trajectory_optimizer.h` line 280 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8OrVXj2jdzGCbSLRRm:-N8Q7XVqDGlCpeF9yUem:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/trajectory_optimizer.h#L280)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

I like these are private. Why wouldn't the methods above in the public section be private as well?
</blockquote></details>

Done.

**Review by amcastro-tri — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/21)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @vincekurtz)

___
*[`-- commits` line 54 at r4](https://reviewable.io/reviews/vincekurtz/drake/21#-N8QNyUq1TFNyWm-CFhh):*
minor, don't forget to clean up this busy history before merging. 
___
*[`traj_opt/trajectory_optimizer.h` line 245 at r1](https://reviewable.io/reviews/vincekurtz/drake/21#-N8OqnrH7F9aTN4BdYmt:-N8QM-ROEHtixQ4g-XX3:b-t8szwa) ([raw file](https://github.com/vincekurtz/drake/blob/e458ab676de582e19a53c49f31de9e84bd0d90bc/traj_opt/trajectory_optimizer.h#L245)):*
<details><summary><i>Previously, vincekurtz wrote…</i></summary><blockquote>

In the Hessian we have terms like `[d(v_t)/d(q_{t-1})]' * Q * d(v_t)/d(q_t)`. Can we still get away with not building N+?
</blockquote></details>

resolved per f2f. We'll have dense lil matrices for now and evaluate performance later.
___
*[`traj_opt/trajectory_optimizer.h` line 75 at r4](https://reviewable.io/reviews/vincekurtz/drake/21#-N8QLfEY20B7gcagrfu_:-N8QLfEY20B7gcagrfua:b-8etuto) ([raw file](https://github.com/vincekurtz/drake/blob/1d3f8183b4d1e89eb337fd8a1a572326c1fb8bf5/traj_opt/trajectory_optimizer.h#L75)):*
> ```objc
>    * @param state optimizer state to update.
>    */
>   void UpdateCache(const TrajectoryOptimizerState& state) const;
> ```

Is the intended workflow to call `UpdateCache()`? or will only the optimizer call this in the implementation? if so, make it private?
___
*[`traj_opt/trajectory_optimizer.cc` line 69 at r4](https://reviewable.io/reviews/vincekurtz/drake/21#-N8QMNVZ5cxcWtVTyNeK:-N8QMNVZ5cxcWtVTyNeL:b-h2hajt) ([raw file](https://github.com/vincekurtz/drake/blob/1d3f8183b4d1e89eb337fd8a1a572326c1fb8bf5/traj_opt/trajectory_optimizer.cc#L69)):*
> ```cpp
> }
> 
> double TrajectoryOptimizer::CalcCost(
> ```

why do we need this version of CalcCost() now? the one with the state does all we need?
___
*[`traj_opt/trajectory_optimizer.cc` line 388 at r4](https://reviewable.io/reviews/vincekurtz/drake/21#-N8QNG_QEU57dSFM_SrO:-N8QNG_QEU57dSFM_SrP:b8hlo04) ([raw file](https://github.com/vincekurtz/drake/blob/1d3f8183b4d1e89eb337fd8a1a572326c1fb8bf5/traj_opt/trajectory_optimizer.cc#L388)):*
> ```cpp
>     const TrajectoryOptimizerState& state) const {
>   TrajectoryOptimizerCache& cache = state.mutable_cache();
>   TrajectoryOptimizerWorkspace* workspace = &state.workspace;
> ```

minor, it's a good practice to get a reference whenever "pointer semantics" (c++ guru buzzworld for, "do I need to check for nullptr?") is not needed. That is, here a c++ guru would write instead `TrajectoryOptimizerWorkspace& workspace = state.workspace`, and then you dereference whenever you need a pointer with `&workspace`. That has the nice effect that out of context you can quickly tell which variables are const inputs and which ones are mutable outputs.
___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 25 at r4](https://reviewable.io/reviews/vincekurtz/drake/21#-N8QNp80DULwGCrJ58Xf:-N8QNp814yrhdRGXy2re:b-1ordsh) ([raw file](https://github.com/vincekurtz/drake/blob/1d3f8183b4d1e89eb337fd8a1a572326c1fb8bf5/traj_opt/test/trajectory_optimizer_test.cc#L25)):*
> ```cpp
>   TrajectoryOptimizerTester() = delete;
> 
>   static double CalcCost(const TrajectoryOptimizer& optimizer,
> ```

do we want to test this? why not to simply test the public API?

**Review by vincekurtz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/21)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @amcastro-tri)

___
*[`traj_opt/trajectory_optimizer.h` line 75 at r4](https://reviewable.io/reviews/vincekurtz/drake/21#-N8QLfEY20B7gcagrfu_:-N8QP9PjDtdQj1JqDUDB:bhdjyrp) ([raw file](https://github.com/vincekurtz/drake/blob/1d3f8183b4d1e89eb337fd8a1a572326c1fb8bf5/traj_opt/trajectory_optimizer.h#L75)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

Is the intended workflow to call `UpdateCache()`? or will only the optimizer call this in the implementation? if so, make it private?
</blockquote></details>

Done, made private. 
___
*[`traj_opt/trajectory_optimizer.cc` line 69 at r4](https://reviewable.io/reviews/vincekurtz/drake/21#-N8QMNVZ5cxcWtVTyNeK:-N8QPErb1khXEnWz24cW:b-m8ij1l) ([raw file](https://github.com/vincekurtz/drake/blob/1d3f8183b4d1e89eb337fd8a1a572326c1fb8bf5/traj_opt/trajectory_optimizer.cc#L69)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

why do we need this version of CalcCost() now? the one with the state does all we need?
</blockquote></details>

I had been using this for finite differences. Removed now. 
___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 25 at r4](https://reviewable.io/reviews/vincekurtz/drake/21#-N8QNp80DULwGCrJ58Xf:-N8QTbjeB5L9IlypEFKj:bmm0l4h) ([raw file](https://github.com/vincekurtz/drake/blob/1d3f8183b4d1e89eb337fd8a1a572326c1fb8bf5/traj_opt/test/trajectory_optimizer_test.cc#L25)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

do we want to test this? why not to simply test the public API?
</blockquote></details>

I found it easier to cook up an example where I know the exact cost using this API rather than the public API. Plus I had this test from before anyway, so figured I'd just leave it in.

**Review by amcastro-tri — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/21#-:-N8QYwv88CU8tGYYuM8Z:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vincekurtz)

**Pull request merged**
