### PR TITLE
Templatize everything for Autodiff

### PR DESCRIPTION
**Pull request by vincekurtz**
Templatizes the solver so it can be instantiated with either `double` or `AutoDiffXd`. 

For actual trajectory optimization we'll just use `double`, but having `AutoDiffXd` available will allow us to test our Hessian computations.

---
This change is [Reviewable](https://reviewable.io/reviews/vincekurtz/drake/22)

### CODE REVIEW

**Review by vincekurtz — COMMENTED** [review]
+@amcastro-tri for feature review please

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/22#-:-N8QiiZD2qJsJJgFxYVk:brbsdox)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @amcastro-tri)

**Review by amcastro-tri — CHANGES_REQUESTED** [review]
Nice!

The only thing that you need here is a cc per header and place the DRAKE_DEFINEs in the corresponding source instead.

> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/22#-:-N8TuTHBAqkV5QCtfQjo:bqvz34y)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @vincekurtz)

___
*[`traj_opt/inverse_dynamics_partials.h` line 82 at r3](https://reviewable.io/reviews/vincekurtz/drake/22#-N8TuQtaCptfYTuQ0XrX:-N8TuQtaCptfYTuQ0XrY:b-fy07yl) ([raw file](https://github.com/vincekurtz/drake/blob/f94a4748a01a1227451b15c5019ce4164171faea/traj_opt/inverse_dynamics_partials.h#L82)):*
> ```objc
> }  // namespace drake
> 
> DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_NONSYMBOLIC_SCALARS(
> ```

move to cc.
___
*[`traj_opt/trajectory_optimizer_state.h` line 130 at r3](https://reviewable.io/reviews/vincekurtz/drake/22#-N8TtZPO49I2H1yhTYjX:-N8TtZPP5HpwqqpsZzwO:bnncbmo) ([raw file](https://github.com/vincekurtz/drake/blob/f94a4748a01a1227451b15c5019ce4164171faea/traj_opt/trajectory_optimizer_state.h#L130)):*
> ```objc
> }  // namespace drake
> 
> DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_NONSYMBOLIC_SCALARS(
> ```

per f2f, move to its own cc.
___
*[`traj_opt/trajectory_optimizer_workspace.h` line 74 at r3](https://reviewable.io/reviews/vincekurtz/drake/22#-N8TtcdSBpa_wZQkCC-g:-N8TtcdSBpa_wZQkCC-h:b-2t04yt) ([raw file](https://github.com/vincekurtz/drake/blob/f94a4748a01a1227451b15c5019ce4164171faea/traj_opt/trajectory_optimizer_workspace.h#L74)):*
> ```objc
> }  // namespace drake
> 
> DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_NONSYMBOLIC_SCALARS(
> ```

move to cc
___
*[`traj_opt/velocity_partials.h` line 42 at r3](https://reviewable.io/reviews/vincekurtz/drake/22#-N8Tt-vFAy9Al6EZhPFV:-N8Tt-vFAy9Al6EZhPFW:bnncbmo) ([raw file](https://github.com/vincekurtz/drake/blob/f94a4748a01a1227451b15c5019ce4164171faea/traj_opt/velocity_partials.h#L42)):*
> ```objc
> }  // namespace drake
> 
> DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_NONSYMBOLIC_SCALARS(
> ```

per f2f, move to its own cc.
___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 81 at r3](https://reviewable.io/reviews/vincekurtz/drake/22#-N8TtzEICu9G3A2ruAyF:-N8TtzEICu9G3A2ruAyG:b-1b3uo0) ([raw file](https://github.com/vincekurtz/drake/blob/f94a4748a01a1227451b15c5019ce4164171faea/traj_opt/test/trajectory_optimizer_test.cc#L81)):*
> ```cpp
> using test::LimitMalloc;
> 
> GTEST_TEST(TrajectoryOptimizerTest, AutodiffGradient) {
> ```

btw, nice test!
___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 135 at r3](https://reviewable.io/reviews/vincekurtz/drake/22#-N8Tu2HD3iiD9I6qhn2c:-N8Tu2HE0VAE28_HTRQ5:b-gcb272) ([raw file](https://github.com/vincekurtz/drake/blob/f94a4748a01a1227451b15c5019ce4164171faea/traj_opt/test/trajectory_optimizer_test.cc#L135)):*
> ```cpp
>   state_ad.set_q(q_ad);
> 
>   AutoDiffXd cost_ad = optimizer_ad.CalcCost(state_ad);
> ```

maybe in this PR or in a different one if you want, see to play with the `math::gradient()` function.

**Review by amcastro-tri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/22#-:-N8TudBZ3_X0bSfgJ1Sd:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @vincekurtz)

**Review by vincekurtz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/22)* status: 4 of 13 files reviewed, 5 unresolved discussions (waiting on @amcastro-tri)

___
*[`traj_opt/inverse_dynamics_partials.h` line 82 at r3](https://reviewable.io/reviews/vincekurtz/drake/22#-N8TuQtaCptfYTuQ0XrX:-N8TzuGC5zE9j2edhY3M:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/f94a4748a01a1227451b15c5019ce4164171faea/traj_opt/inverse_dynamics_partials.h#L82)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

move to cc.
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer_state.h` line 130 at r3](https://reviewable.io/reviews/vincekurtz/drake/22#-N8TtZPO49I2H1yhTYjX:-N8TzuytB5EYB0vvm9qN:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/f94a4748a01a1227451b15c5019ce4164171faea/traj_opt/trajectory_optimizer_state.h#L130)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

per f2f, move to its own cc.
</blockquote></details>

Done.
___
*[`traj_opt/trajectory_optimizer_workspace.h` line 74 at r3](https://reviewable.io/reviews/vincekurtz/drake/22#-N8TtcdSBpa_wZQkCC-g:-N8Tzw-P6XK__M0VTfI4:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/f94a4748a01a1227451b15c5019ce4164171faea/traj_opt/trajectory_optimizer_workspace.h#L74)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

move to cc
</blockquote></details>

Done.
___
*[`traj_opt/velocity_partials.h` line 42 at r3](https://reviewable.io/reviews/vincekurtz/drake/22#-N8Tt-vFAy9Al6EZhPFV:-N8Tzwrx78i_1aGfqNnC:b-896fix) ([raw file](https://github.com/vincekurtz/drake/blob/f94a4748a01a1227451b15c5019ce4164171faea/traj_opt/velocity_partials.h#L42)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

per f2f, move to its own cc.
</blockquote></details>

Done.
___
*[`traj_opt/test/trajectory_optimizer_test.cc` line 135 at r3](https://reviewable.io/reviews/vincekurtz/drake/22#-N8Tu2HD3iiD9I6qhn2c:-N8TzzKF9i3mHUZoqd1F:b-g3owk) ([raw file](https://github.com/vincekurtz/drake/blob/f94a4748a01a1227451b15c5019ce4164171faea/traj_opt/test/trajectory_optimizer_test.cc#L135)):*
<details><summary><i>Previously, amcastro-tri (Alejandro Castro) wrote…</i></summary><blockquote>

maybe in this PR or in a different one if you want, see to play with the `math::gradient()` function.
</blockquote></details>

per f2f `math::jacobian()` and `math::hessian()` are the wrong tools here, b/c they require converting the plant to a new scalar type.

**Pull request merged**
