### PR TITLE
Adds option to use PETSc

### PR DESCRIPTION
**Pull request by amcastro-tri**
Implements option to choose a PETSc solver.
Unfortunately, in practice the PETSc solvers we have so far are very unstable due to the large condition numbers. 
However, this seems a useful pattern if we add other solvers (GSL?) or if we add options for other PETSc solvers.

- - -
This change is [Reviewable](https://reviewable.io/reviews/vincekurtz/drake/54)

### CODE REVIEW

**Review by amcastro-tri — COMMENTED** [review]
+@vincekurtz for review please.

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/54#-:-NCbJeeDEL0mChSiNQAn:b5fk94)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @vincekurtz)

**Review by vincekurtz — APPROVED** [review]
You were not kidding about the PETSc solvers not being terribly useful - I tried it out and didn't get anything useful for the hopper. Even for the spinner, I get solve times twice as slow as the dense solver (!). But I agree that having the option to switch solvers is great.

:lgtm: 

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/54#-:-NCbNyf12jDpDEg3kgbD:bctaja9)* status: all files reviewed, 2 unresolved discussions (waiting on @amcastro-tri)

___
*[`traj_opt/BUILD.bazel` line 85 at r1](https://reviewable.io/reviews/vincekurtz/drake/54#-NCbKxxx3zoBLO7yHRnU:-NCbKxxy6JARLQSeBI-5:b5bzzeb) ([raw file](https://github.com/vincekurtz/drake/blob/2c1350669fb93a718287df5695c4cb378692f942/traj_opt/BUILD.bazel#L85)):*
> ```Starlark
>         ":velocity_partials",
>         "//common:essential",
>         "//common:profiler",        
> ```

nit, whitespace. I have linters enabled, so `bazel test //traj_opt/...` will catch this sort of thing I think
___
*[`traj_opt/solver_parameters.h` line 79 at r1](https://reviewable.io/reviews/vincekurtz/drake/54#-NCbNF6T-WmDHCaBukjp:-NCbNF6T-WmDHCaBukjq:br4059n) ([raw file](https://github.com/vincekurtz/drake/blob/2c1350669fb93a718287df5695c4cb378692f942/traj_opt/solver_parameters.h#L79)):*
> ```objc
>   LinearSolverType linear_solver{LinearSolverType::kPentaDiagonalLu};
> 
>   // Parameters for the PETSc solver. Ignored of linear_solver != kPetsc.
> ```

nit, "if"

**Review by amcastro-tri — COMMENTED** [review]
yeah... You can tell it is the conditioning of the problem by using a larger time step size and less time steps (recall we found out that apparently the condition number goes as κ∼δt⁻⁴). So with smaller time steps I can get the acrobot to actually work with Petsc.

I won't work on this today. So please feel free to address comments and merge.

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/54#-:-NCebXob9tubB40jUHJO:b-vdj8bx)* status: all files reviewed, 2 unresolved discussions (waiting on @amcastro-tri)

**Review by vincekurtz — APPROVED** [review]
SGTM, will do. I'm going to open a new PR to address the comments, since I don't have write access to `amcastro-tri/drake`

> *[Reviewable](https://reviewable.io/reviews/vincekurtz/drake/54#-:-NCee4HJ7lwBpyEWjMty:b-nw1og5)* status: all files reviewed, 2 unresolved discussions (waiting on @amcastro-tri)

**Pull request closed without merging**
